### ISSUE TITLE
How to build a offline go build with tags 'all'

### ISSUE THREAD

**Issue by chakri-stark** [xo/usql#106]
Hi @kenshaw ,
I have some complications as I do not have internet access to some of my servers. So, I would like to know about whether can we get all the drivers and move these folders to another server(another OS like AIX, Freebsd and SunOs) and build it without internet access.
Any help regarding this is highly appreciated. I am in dire need of this. Please let me know if any possibilities to achieve this.

**Comment by kenshaw** [comment]
If you disable any CGO based driver, then you should be able to build it on a separate host and just copy the binary over, as most of the drivers are 100% Go. Alternately, if you need the CGO based drivers, you will likely need to build on the same platform for which you're targeting. I'd suggest deleting `$GOPATH` (or at least moving it temporarily), then doing the following:

```sh
$ export GOPATH=/tmp/gopath
$ export GO111MODULES=off
$ GOARCH=<whatever> GOOS=<whatever> go get -u -tags all github.com/xo/usql
```

After the above, `/tmp/gopath` should be populated with every dependency needed to build for your OS/ARCH combination.

**Comment by chakri-stark** [comment]
Hi @kenshaw ,
I have tried this out but this process failed for the offline build. (maybe because I need all tags with CGO drivers)
But, I have succeeded with the following additional steps:
Once we have done "go get -u -tags all github.com/xo/usql", go to src/github.com/xo/usql and run the go mod download" command and you should be getting a new folder vendor
This should download all the dependencies needed even for CGO drivers.
I have downloaded this in the Linux platform and compiled it in the Windows Platform with no internet.
Note: Windows need tdm-GCC for building CGO drivers

**Comment by kenshaw** [comment]
Is there a specific error message that `go build` is reporting? I've tested `go build -tags all` on macOS, Linux, and Windows. If you have the required dependencies for the CGO deps, it definitely builds on those platforms. There are only 3 drivers that require CGO (`sqlite3`, `oracle`, `odbc`). If it's not building for whatever reason, you can try building without any drivers:

```sh
$ go build -tags no_base
```

In case there is some kind of other problem/issue, and you don't want to complicate it with the drivers. Of course, a built `usql` without any drivers won't be able to connect to a database.
