### ISSUE TITLE
Cross compiling for any other platform is failing

### ISSUE THREAD

**Issue by chakri-stark** [xo/usql#107]
The compilation works fine in Linux but while cross-compiling for freebsd or SunOS, I am facing the following errors as attached in log 
[cross.log](https://github.com/xo/usql/files/3951920/cross.log)

**Comment by kenshaw** [comment]
You'll need to disable the C-based drivers (SQLite3, ODBC, Oracle), and/or have a proper/full cross toolchain available for the platform you're targeting. 

Try the following:
```sh
$ cd $GOPATH/src/github.com/xo/usql
$ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags 'all,no_sqlite3,no_oracle,no_odbc'
```
Change the `GOOS` and `GOARCH` for your target OS/Platform. For what it's worth, I tried the above on Darwin (macOS) and was able to build a Linux binary that worked properly. As I don't have FreeBSD/SunOS (do you mean Solaris, btw?) installed to test with, I'll leave it up to you. 

Good luck!

**Comment by chakri-stark** [comment]
Hi @kenshaw ,
Thanks for the response. I currently have access to FreeBSD and Solaris servers. I will try this out and will update here how it goes.
