### ISSUE TITLE
How to set up a connection if there is "#" character in username or password 

### ISSUE THREAD

**Issue by chakri-stark** [xo/usql#109]
Hi @kenshaw 
I was unable to connect when my username or password contains the "#" character. Is there a way that we can get past this? Thanks in advance.

**Comment by kenshaw** [comment]
Use URL encoding.
```sh
(not connected)=> \connect postgres://user:pass%23@host
```
`%23` is the character encoding (I think) for the hash symbol (`#`).

**Comment by chakri-stark** [comment]
Hi @kenshaw , How can I do it in a non-interactive mode as I need to call this via a C application.

**Comment by kenshaw** [comment]
Why would you use `usql` from a C application? Why not just use the C library for whatever database you're using? Regardless, you'd be able to URL encode any username/password in C, and then pass it that way.

**Comment by chakri-stark** [comment]
As we need to connect to MySQL, mssql, oracle, psql, db2, Hana and tibero to process the server requests, we preferred this tool and integrated in c code instead of writing library calls to every database separately.
I have tested the way you have mentioned above and it works!! Thanks a lot!!

**Comment by kenshaw** [comment]
Ok. Well good luck with it! For what it's worth, using the ODBC library sounds like a better fit than `usql`, but great to hear someone is making use of it. Cheers.

**Comment by chakri-stark** [comment]
Thanks a ton!! I just love this tool! I have read your conversations regarding autocomplete back in 2017 in a forum and I would love to contribute if any needed.
