### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by jimmyegd** [xo/usql#120]
I have installed on raspberry pi, it's ok when i am connecting to sqlite, but when i am trying to connect to sql server, it gives this error, 
Login error: read tcp <local_ip>:<any_local_port> -> <server_ip>:1433: read: connection reset by peer
It happens the same when i connect from ubuntu 18.04
The command was
./usql mssql://dbUser:dbPassword@server_IP:1433/DbName

i use dbeaver to manage all my databases and i am able to connect from ubuntu 18.04 to windows7 sql sever

**Comment by jimmyegd** [comment]
I test it with postgres and it's ok, the only problem is with mssql, i really like this tool

**Comment by calebeaires** [comment]
I am facing the same problem. SQL server version 2008, any news?

**Comment by kenshaw** [comment]
@calebeaires + @jimmyegd I don't have Windows 7 + SQL Server 2008 to test this with. I really would need more help from you to debug and figure out the issue. `usql` simply uses [this package](https://github.com/denisenkom/go-mssqldb) for its connection. If one of you could try testing that driver with a minimal Go application and reporting back the error, I'd be able to fix it. For what it's worth, I just tested this against SQL Server Express 2019 on Linux (using Microsoft's published Docker image) and it worked fine without any connection issues. 

Additionally, its worth mentioning that I'm using this from the command-line on Linux. I'm guessing you're using `usql` from Windows. As such, it could be related to something else entirely that I'm not aware of.

**Comment by calebeaires** [comment]
I just fix the issue using this: `encrypt=disable`

```
usql --csv  mssql://user:password@my_ip:1433/database?encrypt=disable
```
