### ISSUE TITLE
Build Failure With pgx Driver

### ISSUE THREAD

**Issue by levouh** [xo/usql#121]
On Fedora 31:

```
$ go version
go version go1.13.10 linux/amd64
$ go get -u -tags all github.com/xo/usql
...
go/src/github.com/xo/usql/drivers/pgx/pgx.go:30:21: undefined: pgx.PgError
go/src/github.com/xo/usql/drivers/pgx/pgx.go:36:21: undefined: pgx.PgError
```

I am not very familiar with Go, but doing some searching it looks like this is a problem with the version of `pgx` being used, and would perhaps be fixed by changing `pgx.PgError` to `pgconn.PgError`?

Again, this is with a very surface level knowledge set, so I could easily be doing something else wrong. Any ideas?

**Comment by kenshaw** [comment]
Do you have `GO111MODULES=off` or some other environment change? I just checked this, and I don't see any specific problems/issues here.

**Comment by levouh** [comment]
I'd never used Go before this, so the first step was:

```
$ sudo dnf install golang
```

followed immediately by the above statements.

```
$ printenv | grep -i go
```

also shows nothing of interest.

**Comment by levouh** [comment]
However, it appears to have worked when doing:

```
GO111MODULE=on go get -u -tags all github.com/xo/usql
```

so perhaps the default has changed or similar.

**Comment by kenshaw** [comment]
I see -- yes, it's hard for me to encounter these issues, because the way Go handles dependencies now is different than how it was before. No worries -- after your issue, I noticed that `pgx` has reorganized the core errors into Go 1.13 style error handling, and refactored into multiple packages. Additionally, it now requires use of the `/vX` syntax in package declarations. I'll push an update shortly that should fix this issue. Glad to hear you got it working locally otherwise.

**Comment by levouh** [comment]
I've only had a chance to mess around with this a bit, but so far this is a wonderful project so thanks for the work as well as the quick response.

I also believe that my above statement was incorrect, because while the binary was built, it doesn't appear that the same set of drivers was included. I feel like I must have accidentally done:

```
GO111MODULE=on go get -u -tags oracle github.com/xo/usql
```

hence why it worked. However, now when I use `-tags all` it works and builds with all the drivers as expected. Thanks!

**Comment by kenshaw** [comment]
@levouh glad to hear that. I've already pushed an update, so this should be working. Good luck!

**Comment by levouh** [comment]
Yep, I tested it with your updates and everything looks good. Thanks again.
