### ISSUE TITLE
JSON output option is not being applied

### ISSUE THREAD

**Issue by calebeaires** [xo/usql#124]
Different from the option --csv, the --json **does not produce the correct output**. I have read the lib to find what I am missing but seams everything is ok.

`usql my://root:root@localhost/base -w --command "select * from flats"  --json
`

Is this feature really disponible?

**Comment by nineinchnick** [comment]
As a workaround you can set a specific format with `-P format=json`:
```
% usql sqlite://:memory: -c "select 1,2,3;" --set SHOW_HOST_INFORMATION=false -P format=json                            
[{"1":1,"2":2,"3":3}]
```
