### ISSUE TITLE
Are there plans to implement `\timing` command?

### ISSUE THREAD

**Issue by shekhargulati** [xo/usql#126]
One of the useful commands in `psql` is `\timing` to show query times. Are there any plans to implement it?

**Comment by kenshaw** [comment]
@shekhargulati the goal of the project is to, yes, be compatible with `psql`, including (where feasible) all meta commands. As such, it's fairly straightforward to implement the command, and if you're able to, please give a go at implementing it and submitting a PR! Assuming the implementation is good, it will be accepted into the source.

**Comment by shekhargulati** [comment]
@kenshaw I will pick it up and raise PR.

**Comment by kenshaw** [comment]
This is now on the master branch. A release will be cut soon. Thanks to @nineinchnick for his work here.
