### ISSUE TITLE
usql docker image

### ISSUE THREAD

**Issue by kerphi** [xo/usql#128]
It would be great to have usql embeded in a docker image.

Thanks to this docker image it would be another way to install/uninstall the client (easily).

**Comment by ilaipi** [comment]
I built one:  [ilaipi/xousql-docker](https://github.com/ilaipi/xousql-docker)

**Comment by kenshaw** [comment]
At the moment, I have no plans to build/create/support a docker image for `usql`.

**Comment by davidecavestro** [comment]
I just published https://github.com/davidecavestro/usql-docker in the hope it helps someway.
