### ISSUE TITLE
Allow to connect with gocloud to AWS/GCP instances.

### ISSUE THREAD

**Issue by ademariag** [xo/usql#133]
Following what has already happened in https://github.com/cyrilgdn/terraform-provider-postgresql/pull/29 I would like to suggest to add support for connecting natively to GCP (and AWS/Azure) postgres/mysql instances without the need to use use a proxy by leveraging https://gocloud.dev/

I have done an initial test and it seems to work nicely with usql.

If I were to send a patch, would you want me (for `postgres` driver for instance) to create a new driver, or reuse the current one and add gcppostgres as an alias?

Regards
Alessandro

**Comment by kenshaw** [comment]
@ademariag always open to PRs that are well written. I'm not sure how you'd be able to not use some kind of a proxy, which on the surface appears that's what the GoCloud SDK is doing (or some lazy variation of that).

**Comment by ademariag** [comment]
@kenshaw please let me know what you think about my proposed solution
