### ISSUE TITLE
Implement introspection metacmds (\d*, others)

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#149]
All the various introspection metacmds need to be implemented.

For PostgreSQL, partial work [has been done here](https://github.com/xo/pgdesc), however it is not likely that the code in its current state will be completed, as a `regexp` based conversion is not tenable in the long run. While that code can be salvaged, an ideal implementation would be to extract the pertinent functions from the postgres source, then transform that using clang's `--ast-dump` (to json). Then, use Go to traverse the generated C AST and generate the necessary code.

Additionally, the other 4 major databases (SQLite3, MySQL, MS SQL, Oracle) need to have introspection commands implemented, which likely means painstaking and time consuming research to determine the correct. Since MySQL is open source and supports similar commands as `psql` in its command-line client, it may be possible to also write a generation script for it as well. A separate, generic `information_schema` one should also be written to be used as default for the non major databases.

**Comment by nineinchnick** [comment]
Can we close this now and keep #57 for 100% compatibility with psql?
