### ISSUE TITLE
Fix PAGER

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#155]
Proper PAGER support needs to be completed for `psql` compatibility.

**Comment by nineinchnick** [comment]
Relevant psql code: https://github.com/postgres/postgres/blob/ca3b37487be333a1d241dab1bbdd17a211a88f43/src/interfaces/libpq/fe-print.c#L149

**Comment by nineinchnick** [comment]
This is a dup of #112

I also stumbled upon https://github.com/okbob/pspg which we might consider mentioning in the README

**Comment by kenshaw** [comment]
@nineinchnick I'm not sure why `pspg` is relevant? By `PAGER` support, `usql` should support the shell's defined `PAGER` (if any). What `psql` does is pass the output of a query (via a pipe) to the user's defined `$ENV{PAGER}` variable, and has some added options for setting the a minimum number of returned rows/output before passing the output to the `PAGER`.
