### ISSUE TITLE
Add CSV database support

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#156]
Add ability to read/modify CSV files using a CSV extension to other database.

There are a number of possible implementation solutions, but the most straightforward is probably by writing a CSV vtable extension for SQLite3.

**Comment by pashagolub** [comment]
Hello, don't you think using this driver is a preferable way? Thanks
https://github.com/mithrandie/csvq-driver

**Comment by nineinchnick** [comment]
Would you be interested in working on a pull request?

**Comment by pashagolub** [comment]
I can try if it's not urgent :)

**Comment by nineinchnick** [comment]
Yes please! Contributions would be very welcomed. And it'll get done when
it's done.
