### ISSUE TITLE
Implement auto for \x

### ISSUE THREAD

**Issue by nineinchnick** [xo/usql#168]
`psql` allows to set `\x auto`, instead of just `on` or `off`. It should use the extended format when the output is wider than the current terminal - that is there are too many columns. This requires fetching current terminal dimensions, so it's kinda similar to #155 (and #112?) - maybe we'll have to wrap the writer passed to tblfmt or pass this as parameters.

PS. Should we create such issues in https://github.com/xo/tblfmt?  I don't have any preference.

**Comment by kenshaw** [comment]
For what it's worth, yes, it'd entirely in `tblfmt`, and would be easy to implement. A tracking ticket here is prudent as well.
