### ISSUE TITLE
date-format of FireBird queries

### ISSUE THREAD

**Issue by Rebewslin** [xo/usql#184]
Hi, I'm using usql 0.8.2 for querying a FireBird database on my Mac (10.13.6). 
Because the released version always runs on an error (dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.68.dylib), I compiled my own version with "go get -u -tags most github.com/xo/usql".

This version works fine and is stable and really fast, thank you! One issue occurs: Querying a date field (also with separate casting as date) always returns dates in this format: **2019-10-09T00:00:00+02:00**.
It doesn't matter if I use unaligned, CSV or JSON-output, I never get the expected date in standard-format: **2019-10-09**. Of course I can cast the date as varchar(10), but this only a workaround. Hope you can fix it.

Nils

**Comment by kenshaw** [comment]
On your first issue: if you're on macOS, I'd recommend using `brew` to install/use `usql`, and not use the distributed binaries. If you'd like to use the distributed binaries, then this should fix your dependency issue:

```sh
$ brew install icu4c
```

In future releases, I'll make a note of this in the `README.md` as well as see if the `icu4c` library can be built into the binary statically.

On your second issue:

At the moment the time formatting functionality is only being respected/recognized for aligned table output, and additionally it's worth noting that it would only be supported if the underlying database driver converts time values to Go's standard `time.Time` type (not all do). I agree that this should be a universally recognized option and I will endeavor to make this possible for non aligned table output, but separately, the work to enable/verify this for every database driver goes far outside the scope/goals of this project. As a workaround, I would suggest using the database's native time formatting functionality in your SQL queries to get the desired/expected output until `usql` better supports this for non aligned table output format options.

**Comment by dsedivec** [comment]
> At the moment the time formatting functionality is only being respected/recognized for aligned table output, and additionally it's worth noting that it would only be supported if the underlying database driver converts time values to Go's standard `time.Time` type (not all do).

Does this mean that, for all supported data sources, usql will always output a date *and* time, even when the data type is `DATE` (rather than e.g. `TIMESTAMP`)?

I only ask because I was surprised when `SELECT CAST('2021-01-01' AS DATE)` printed a result of `2021-01-01T00:00:00Z` on MS SQL Server.

**Comment by kenshaw** [comment]
@dsedivec Yes. `usql` is written in Go, and there is only the standard library's `time.Time` type for dealing with concepts of "Dates". Whether it's a date/timestamp/... if the underlying Go driver returns a `time.Time`, then `usql` will format it using the `\pset time` setting. I would suggest changing your query to use the underlying database's time/date formatting functionality in your query if you'd like different output.
