### ISSUE TITLE
Error executing valid ALTER AUTHORIZATION command on MS SQL Server

### ISSUE THREAD

**Issue by MichaelF25** [xo/usql#190]
Trying to update the ownership of a database in MS SQL Server via `usql` but fails. The command works if executed in Microsoft SQL Server Management Studio.

Example output using latest Microsoft SQL Server 2019 docker container:

```
$ usql -c "ALTER AUTHORIZATION ON DATABASE::mydb TO myuser;" sqlserver://sa:sapassword@localhost:1433
Connected with driver mssql (Microsoft SQL Server 15.0.4102.2, RTM, Developer Edition (64-bit))
error: mssql: sql: expected 1 arguments, got 0
```

**Comment by nineinchnick** [comment]
According to https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-authorization-transact-sql?view=sql-server-ver15 it's valid syntax:
```
ALTER AUTHORIZATION
    ON [ <class_type>:: ] entity_name
    TO { principal_name | SCHEMA OWNER }
    [;]

<class_type> ::=
     {
      OBJECT | ASSEMBLY | ASYMMETRIC KEY | AVAILABILITY GROUP | CERTIFICATE
    | CONTRACT | TYPE | DATABASE | ENDPOINT | FULLTEXT CATALOG
    | FULLTEXT STOPLIST | MESSAGE TYPE | REMOTE SERVICE BINDING
    | ROLE | ROUTE | SCHEMA | SEARCH PROPERTY LIST | SERVER ROLE
    | SERVICE | SYMMETRIC KEY | XML SCHEMA COLLECTION
     }
```

But it looks like it's the mssql driver that's trying to do param interpolation, not `usql`.

Can you check if skipping the type would work? As in `ALTER AUTHORIZATION ON mydb TO myuser;`.

**Comment by kenshaw** [comment]
@nineinchnick this appears to be a simple fix. We need to change the driver name from `mssql` to `sqlserver`. Apparently this behavior is listed/known (see the `README.md` in the project). I'll try/test this to see if that's the issue, or if the underlying driver does indeed do interpolation.

**Comment by kenshaw** [comment]
I apologize; I should have [left a link](https://github.com/denisenkom/go-mssqldb#query-parameter-token-replace-driver-mssql).

**Comment by kenshaw** [comment]
Changing the name of the internal driver passed to the Go SQL library indeed fixes this. Very frustrating that this driver decided to do that. I personally would have changed the namespace (URL) of the package, and/or just made the behavior non-backwards compatible (and not pinned to the name of the driver), and possibly provided an option to reenable the old/defunct behavior. Anyways, I'll be pushing a fix for this shortly.

**Comment by kenshaw** [comment]
@MichaelF25 this won't go out as a binary build until we're ready for the next release. That may happen "soon". If you really need this functionality, please build/install from source or use `go install -tags most github.com/xo/usql@master`
