### ISSUE TITLE
Execute the command on each row

### ISSUE THREAD

**Issue by caobingsheng** [xo/usql#199]
like `/each` `systemcmd rowcol1 rowcol2 ... `

**Comment by nineinchnick** [comment]
See if `\g |systemcmd` does what you want. It'll pass the results of the query as standard input to the `systemcmd` command. If you need to pass the results of the query as separate arguments, use `xargs`.

It was just recently implemented in #194 so it's only available on master branch, not in any released version.

**Comment by caobingsheng** [comment]
@nineinchnick thanks ! is really helpful for me.

**Comment by nineinchnick** [comment]
Happy to help! If that solves the problem, can you close this issue?
