### ISSUE TITLE
Proposal: using env variable USQLDSN

### ISSUE THREAD

**Issue by atdichev** [xo/usql#226]
Just like **psql** uses **PGHOST**, **PGDATABASE** etc. maybe we can have a variable **USQLDSN**(for example) which sets the datasource name

For example:

```
export USQLDSN=pg://user:pass@host/database
./usql
Connected with driver postgres (PostgreSQL ....

```

**Comment by kenshaw** [comment]
@atdichev Thanks for the suggestion. I don't think this fits in well with how `psql` and `usql` recognize environment variables.

If this is something you'd like to enable on your command-line, you could set a bash alias to pass that environment variable as the first parameter to `usql`, and/or just pass it directly:

```sh
$ usql $USQLDSN
```
