### ISSUE TITLE
enhancement: recognize `USE` statements on command completion

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#239]
When connecting to a database (such as a MySQL database) and not specifying the database in the URL path, the tab/command completion does not work. A simple example:

```sh
(not connected)=> \c mysql://user:pass@host/
my:user@host=> USE my_database;
USE
my:user@host=> select * from
```

If entering a `<tab>` after the above, the expected behavior is that the completion menu comes up. This does not happen currently. However, it's worth noting it does when specifying the connecting database:

```sh
(not connected)=> \c mysql://user:pass@host/my_database
my:user@host/my_database=> select * from
```
Need to rework the drivers so that the tab completion works as expected after a `USE` (or other database equivalents).

**Comment by nineinchnick** [comment]
I need to investigate this more. The completer filters out objects that should not be visible by adding a condition using an expression, not a predefined value. So it should be evaluated on the server, in the context of the open connection. In case of mysql this is `DATABASE()`.

I noticed same issue a long time ago with the Trino driver.

**Comment by nineinchnick** [comment]
The completer gets initialized when opening a connection. Maybe we need to reinitialize it after USE. We do already have some system to detect query type.
