### ISSUE TITLE
Build fails due to missing xo/xoutil

### ISSUE THREAD

**Issue by cf-sewe** [xo/usql#243]
As a first time user, I tried to install usql via go:

```GO111MODULE=on go get github.com/xo/usql```

However it is asking me for GitHub username/password. In verbose mode I saw the reason is the now missing `xo/xoutil` repository:

```
# GO111MODULE=on go get github.com/xo/usql
go: github.com/xo/usql upgrade => v0.8.2
Username for 'https://github.com': Username for 'https://github.com':
Password for 'https://github.com': Password for 'https://github.com':
Username for 'https://github.com':

Password for 'https://github.com':
go get: github.com/xo/usql@v0.8.2 requires
        github.com/xo/xoutil@v0.0.0-20171112033149-46189f4026a5: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/076de485f6bfc7a8e444ab6a676f8b3bebc02186cfe92720dd78cec82eafcc82: exit status 128:
        remote: Repository not found.
        fatal: Authentication failed for 'https://github.com/xo/xoutil/'
```

Could you readd the repo, or maybe release a new version without this depedency?

**Comment by kenshaw** [comment]
This package has been deleted. Apologies. Please try `GO111MODULE=on go get github.com/xo/usql@master` instead.

**Comment by cf-sewe** [comment]
It also fails, but due to modernc:

```
# GO111MODULE=on go get github.com/xo/usql@master
go: github.com/xo/usql master => v0.0.0-20210427073305-9792fc8d1db0
Username for 'https://github.com':
Password for 'https://github.com':
go get: github.com/xo/usql@v0.0.0-20210427073305-9792fc8d1db0 requires
        modernc.org/b@v1.0.1: reading modernc.org/b/go.mod at revision v1.0.1: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/e4d822a6e5117a941675151e51943e806b98394310c31351bf5d1078e126484b: exit status 128:
        error: RPC failed; result=22, HTTP code = 422
        fatal: The remote end hung up unexpectedly
```

🤔 is this a temporary error?

**Comment by kenshaw** [comment]
@cf-sewe Are you doing this in a directory/folder that already has a `go.mod`? If so, you can remove the `xoutil` lines from `go.mod` and `go.sum` prior to doing the `go get -u`. If this isn't in a directory/folder with a `go.mod`, I'm not sure what the issue is. This works fine on my system. What version of Go are you using?

**Comment by cf-sewe** [comment]
I am not able to fix it , seems like an infrastructure error. Could be related to cloudflare.

Using ` GIT_CURL_VERBOSE=1 git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*` in the checkout path of `modernc.org/b@v1.0.1` I receive some strange HTTP error. I guess I will try again later.

```
> POST /cznic/b/git-upload-pack HTTP/1.1
User-Agent: git/1.8.3.1
Host: gitlab.com
Accept-Encoding: gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Length: 304

* upload completely sent off: 304 out of 304 bytes
* The requested URL returned error: 422 Unprocessable Entity
* Closing connection 1
error: RPC failed; result=22, HTTP code = 422
fatal: The remote end hung up unexpectedly
```

**Comment by kenshaw** [comment]
I'm not sure what your specific problem is. Perhaps check your `GOPROXY` and other Go environment variables. I think you're on a fairly old version of Go, or have somehow disabled Go's module / proxy support for public URLs. I verified on a clean VM that the above was all that is necessary to install (assuming Go is installed somewhere).

**Comment by cf-sewe** [comment]
Just to wrap this up. With the latest release 0.9.0 *and* a update of go to latest official version it is now installing fine on my OS.
The GO version bundled with CentOS 7, was seemingly really too old.
