### ISSUE TITLE
list tables inside schema

### ISSUE THREAD

**Issue by drcode2** [xo/usql#244]
Hi

I want to list tables\views etc , inside schame,
I am connecting to oracle db

how can I use \dt or \d list to specific schame?

**Comment by nineinchnick** [comment]
Can you try `\d schema_name.*`?

**Comment by drcode2** [comment]
> Can you try `\d schema_name.*`?

It worked 
Thank You

**Comment by nineinchnick** [comment]
Yes, use `\?` to list all available commands, with descriptions. Looks like you need `\dv` and `\df`. Feel free to open more issues if you find something that's not working very well.
