### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by AkhilJalagam** [xo/usql#245]
release:  usql-0.9.0-linux-amd64.tar.bz2
os:  arch linux

```
$ usql
./usql: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
```

libraries on my system
```
% ls /usr/lib/libicuuc.so
libicuuc.so@       libicuuc.so.69@    libicuuc.so.69.1*
```

**Comment by kenshaw** [comment]
@AkhilJalagam this is similar to the macOS issue. Just install `libicuuc`. On Arch, that should be `pacman -Su icu`.

**Comment by AkhilJalagam** [comment]
@kenshaw   I already installed it. But it's the latest version libicuuc.so.69 . **usql needs old version ie: libicuuc.so.67**  
do I have to downgrade icu version on my system ?

**Comment by kenshaw** [comment]
@AkhilJalagam sorry about that. Since you're on Arch, it's been pointed out that Arch's packages already have `usql`. I know the `usql-bin` package has been updated by @nineinchnick, so you can try: `pacman -Su usql-bin`.

**Comment by kenshaw** [comment]
@AkhilJalagam BTW -- I don't believe the API has changed between these versions of `libicu`. That means: you can change the path to the library `rpath`, or you can simply put a symlink in your lib folder to the existing version. It should work fine.

**Comment by AkhilJalagam** [comment]
@kenshaw actually i tried arch package first. which is not working. so i used release version and got icu issue.

arch package issue:

% yay -S usql-bin
```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  usql-bin-0.9.0-1

  1 usql-bin                         (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: PKGBUILD up to date, Skipping (1/1): usql-bin
  1 usql-bin                         (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: usql-bin
==> Making package: usql-bin 0.9.0-1 (Fri 30 Apr 2021 12:27:37 PM IST)
==> Retrieving sources...
  -> Found usql-bin-0.9.0.tar.bz2
  -> Found LICENSE
==> Validating source files with sha256sums...
    usql-bin-0.9.0.tar.bz2 ... Passed
    LICENSE ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: usql-bin

```

**Comment by AkhilJalagam** [comment]
> @AkhilJalagam BTW -- I don't believe the API has changed between these versions of `libicu`. That means: you can change the path to the library `rpath`, or you can simply put a symlink in your lib folder to the existing version. It should work fine.

I will try symlink as libicuuc.so.69 -> libicuuc.so.67, and see if it works.
thank you.

**Comment by kenshaw** [comment]
Ok. I'd suggest building from source. As a note, the release versions of `usql` are packed with `upx`. You'll need to decompress it first if you want to mess with the binary.

**Comment by nineinchnick** [comment]
I admit the `usql-bin` package I took over doesn't work correctly. I'll try to figure out how to install the correct version of libicu this weekend.

**Comment by kenshaw** [comment]
@AkhilJalagam thanks to @nineinchnick it looks like we have a working solution to create fully static builds. I'll be doing some tests to check it doesn't break something else somewhere, and then we'll do a point release if everything works fine.
