### ISSUE TITLE
empty variables not shown in `\raw`

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#257]
Empty variables should show in `\raw`.

For example, currently `usql` produces the following output:

```sh
(not connected)=> \set a ''
(not connected)=> select :a
(not connected)-> \p
select 
(not connected)-> \raw
select 
(not connected)->
```

However, on the `\raw` above, it should have shown:

```sh
(not connected)-> \raw
select :a
(not connected)->
```

Comparatively:

```sh
(not connected)=> \set a b
(not connected)=> select :a
(not connected)-> \p
select b
(not connected)-> \raw
select :a
(not connected)->
```

And, it behaves as expected for quoted variables:

```sh
(not connected)=> \set a ''
(not connected)=> select :'a'
(not connected)-> \p
select ''
(not connected)-> \raw
select :'a'
(not connected)->
```

It's worth noting this is not dependent on the length of the variable name:

```sh
(not connected)=> select :aa
(not connected)-> \p
select 
(not connected)-> \raw
select 
(not connected)-> 
```

The reason for this behavior is partly due to the original way that variables were parsed and interpolated (at time of entry). This will require a slight overhaul to how variables are captured and interpolated.

**Comment by nineinchnick** [comment]
This is fixed by https://github.com/xo/usql/commit/f6882c02bb88e7ac5761e6ee420f139d74b58309 and https://github.com/xo/usql/commit/c88eb8dc9e96dba116604b3001715e8dd0652b7b, right?
