### ISSUE TITLE
expand documentation and add more to `\?` command

### ISSUE THREAD

**Issue by kenshaw** [xo/usql#258]
Current `usql` documentation  needs to be expanded to provide the same level of documentation level as `psql`. Additionally, the `\?` command should be able to look up specific help topics. Also, we should make the documentation  available via the `usql.app` website.

This will require effort in a number of ways:

1. Authoring the documentation in a form that can be embedded in both the `usql` command line application, and used for the website
2. Building the simple documentation site and related infrastructure configuration (like Docusaurus and custom cloud-init scripts)
3. Hooking in embedded documentation to the `\?` command, as per `psql`

**Comment by nineinchnick** [comment]
Does this involve writing docs in comments of exported functions/vars? Or a package comment in `doc.go`?
