### ISSUE TITLE
Support for pspg

### ISSUE THREAD

**Issue by yshadow** [xo/usql#260]
I'm using psql like this:
export PAGER="pspg -s 0"
psql -h localhost -U user -d password

Is it possible to add support for pspg?

**Comment by nineinchnick** [comment]
It's already supported, since 0.9.0

**Comment by nineinchnick** [comment]
Check if you have it turned on via `\pset pager on` or `\pset pager always`. You can add this to your `~/.usqlrc` or even copy (symlink) your whole `~/.psqlrc`.
