### ISSUE TITLE
pager should be active

### ISSUE THREAD

**Issue by okbob** [xo/usql#261]
Now, when you support the pager (I tested 0.9.1 and it works very well), I think so pager should be enabled by default.

\pset pager on

**Comment by nineinchnick** [comment]
Note that `psql` has pager enabled by default.

**Comment by nineinchnick** [comment]
@kenshaw recently enabled the pager by default if `PAGER` or `USQL_PAGER` are set to `less` or `more`: https://github.com/xo/usql/commit/e905f59621b6cc5aaef8840fad10585f6b8e4552

Shouldn't it be enabled when those vars are set to any valid binary that's in PATH?

**Comment by okbob** [comment]
I think so this check is not good. If you want to use pager, and the pager doesn't there, then I expect error message. Disabling pager in this case is hiding error, and it is not good idea, I think.

**Comment by kenshaw** [comment]
The `PAGER` variable should be set from the `USQL_PAGER` or `PAGER` environment variables now, and should be enabled as `less` by default if not defined now. If this is not working in the latest `master` commit as expected, please feel free to reopen this issue with more details and I'll look into it further.
