### ISSUE TITLE
\set SHOW_HOST_INFORMATION false" in ~/.usqlrc ignored on Windows

### ISSUE THREAD

**Issue by mloskot** [xo/usql#264]
(Spawned from https://github.com/xo/usql/issues/27#issuecomment-844068805)

On Windows, in PowerShell 7, using usql 0.9.1, the `~/.usqlrc` setting does not seem to have any effect:

```console
PS1> echo "\set SHOW_HOST_INFORMATION false" >> ~/.usqlrc
PS1> cat C:\Users\mateuszl\.usqlrc
\set SHOW_HOST_INFORMATION false
```

```console
PS1> usql oracle://user:pass@server/xepdb1
Connected with driver oracle (<unknown, error: oracle: ORA-00942: table or view does not exist>)
Type "help" for help.

or:user@server/xepdb1=> \q
```

------

The environment variable works though:

```console
PS1> $env:USQL_SHOW_HOST_INFORMATION="false"
PS1> $env:USQL_SHOW_HOST_INFORMATION
false
```

```console
PS1> usql oracle://user:pass@server/xepdb1
Type "help" for help.

or:user@server/xepdb1=> \q
```

**Comment by nineinchnick** [comment]
I spent half hour debugging this and the problem is pretty obvious - the RC file gets read _after_ establishing the connection.

The other problem I had with an invalid command is because when I create `~/.usqlrc` using `echo "\set SHOW_HOST_INFORMATION false" >> ~/.usqlrc` in PowerShell, it writes a BOM, which doesn't get recognized.

**Comment by mloskot** [comment]
Thanks for looking into that.

>  using echo "\set SHOW_HOST_INFORMATION false" >> ~/.usqlrc in PowerShell, it writes a BOM, which doesn't get recognized.

This seems to be dependant on PowerShell version as the [The default value is utf8NoBOM](https://docs.microsoft.com/de-de/powershell/module/Microsoft.PowerShell.Utility/Out-File?view=powershell-7) for  `Out-File` (and its alias `>` and `>>`) in 7 which I'm using.

**Comment by nineinchnick** [comment]
I've got 5.1, I think it's the default in Windows 10. PowerShell 7 looks pretty recent.

**Comment by mloskot** [comment]
Yes, 5.1 is the default.
Not really, 7.0 preview has been out there for two years - I've been using it since and never looked back :)

**Comment by nineinchnick** [comment]
`psql` also processes the rc file _after_ opening a connection: https://github.com/postgres/postgres/blob/master/src/bin/psql/startup.c#L333
Since most commands require an open connection, handling `SHOW_HOST_INFORMATION` might be a special case. If that's true, we can document it and recommend setting it in an environmental variable.

**Comment by mloskot** [comment]
I see. It's also [documented](https://www.postgresql.org/docs/current/app-psql.html) indeed

> psql attempts to read and execute commands from the system-wide startup file (psqlrc) and then the user's personal startup file (~/.psqlrc), after connecting to the database but before accepting normal commands

> we can document it and recommend setting it in an environmental variable.

I think it's already sufficiently documented in the [README.md](https://github.com/xo/usql/blob/fffd7f1a52f50eef7e5807037b4338c74cc8b51f/README.md#host-connection-information)

> This can be disabled by setting the system environment variable `USQL_SHOW_HOST_INFORMATION`
> Additionally, it can be passed via the command-line using -v or --set

There is no mention it can be set in the RC file.

By the way, I've just realised the environment variable is prefixed with `USQL_` while the command line variable is perefixed with `SQL_`, while we are discussing just `SHOW_HOST_INFORMATION`. I haven't chance to read the source code which one is correct though.

**Comment by mloskot** [comment]
> while the command line variable is prefixed with `SQL_`

Please, forget that nonsense. I've got no idea where I took the `SQL_` prefix from.

The code is clear:

- environment variable is  prefixed with `USQL_` (sensible to have 'namespace' for the app variables indeed)

https://github.com/xo/usql/blob/5489327c83874bfbb3cef3b9babacc50148e85f5/env/types.go#L38-L42

- command line variable is not prefixed

https://github.com/xo/usql/blob/5489327c83874bfbb3cef3b9babacc50148e85f5/env/types.go#L49-L51

**Comment by nineinchnick** [comment]
Looks like there's nothing to do here then. You think we can close the issue?

**Comment by mloskot** [comment]
Yes, the issue has been clarified. Thank you!
