### ISSUE TITLE
editor command does not work if EDITOR is not set

### ISSUE THREAD

**Issue by renard** [xo/usql#266]
If the `EDITOR` variable (same with `USQL_EDITOR` and `VISUAL`) is not set, the editor command (`\e`) does not work and ends up with `error: no editor defined`.

I tried setting it up in `~/.usqlrc` but it does not help (however it works for `PAGER`):

```
\set PAGER less
\set EDITOR vim
```

BTW it would be nice to have the ability to set a full command with arguments (such as `\set PAGER "less -S"`) in the config file.

**Comment by nineinchnick** [comment]
Looks like we could set `EDITOR` in vars same as we do for `PAGER` [here](https://github.com/xo/usql/blob/master/env/types.go#L50) and then get it from `All()` [here](https://github.com/xo/usql/blob/master/env/env.go#L73).

For the pager recognizing arguments, could you create a separate issue? We could try to break up the command by spaces here: https://github.com/xo/tblfmt/blob/ed2138f05f5384621038fbf3e3392641bc1a19f8/encode.go#L224

**Comment by jdmendoza** [comment]
I'm experiencing this same issue. How can I get the query to open in an editor if I can't define it? Are there any work arounds?
