### ISSUE TITLE
Error when trying to login to Oracle

### ISSUE THREAD

**Issue by sawan** [xo/usql#27]
```
$ ./bin/usql or://user:pass@MYDB
error: ora: ORA-00942: table or view does not exist
```

My guess is it fails at this query:
```
SELECT version FROM V$INSTANCE;
```

Any ideas?

**Comment by kenshaw** [comment]
What version of Oracle are you using?

**Comment by kenshaw** [comment]
My initial thoughts are:

1) old version of Oracle
2) no permissions for querying the virtual table instance

**Comment by sawan** [comment]
Oracle Version is 12.x -- very current.

Why do we need to query the V table? You are correct, most likely no permission. Can't we just assume a default value if the query fails?

I really went through a lot of trouble getting this to install.

**Comment by kenshaw** [comment]
Sorry for the trouble. I assumed that the user would have access to it. It doesn't actually do anything, other than display the remote version of the Oracle database you're connected to. Since you likely installed from source, I would just suggest commenting out the query there. I'll make a point to add a config variable that can be set via `.usqlrc` or something that will not query the database on connect.

**Comment by sawan** [comment]
Ok thanks for taking a look.

**Comment by kenshaw** [comment]
Reopening this so that I don't forget to implement this ("very soon").

**Comment by kenshaw** [comment]
Apologies that this hadn't been fixed until now -- you can now put `\set SHOW_HOST_INFORMATION false` in your `.usqlrc` file:
```sh
echo "\set SHOW_HOST_INFORMATION false" >> ~/.usqlrc
```
or you can disable it via the environment variable:
```
$ export USQL_SHOW_HOST_INFORMATION=false
$ usql or://....
```

**Comment by sawan** [comment]
Thank you.

**Comment by mloskot** [comment]
@kenshaw On Windows, in PowerShell 7, using usql 0.9.1, the `~/.usqlrc` setting does not seem to have any effect:

```console
PS1> echo "\set SHOW_HOST_INFORMATION false" >> ~/.usqlrc
PS1> cat C:\Users\mateuszl\.usqlrc
\set SHOW_HOST_INFORMATION false
```

```console
PS1> usql oracle://user:pass@srerver/xepdb1
Connected with driver oracle (<unknown, error: oracle: ORA-00942: table or view does not exist>)
Type "help" for help.

or:user@srerver/xepdb1=> \q
```

------

The environment variable works though:

```console
PS1> $env:USQL_SHOW_HOST_INFORMATION="false"
PS1> $env:USQL_SHOW_HOST_INFORMATION
false
```

```console
PS1> usql oracle://user:pass@srerver/xepdb1
Type "help" for help.

or:user@srerver/xepdb1=> \q
```

**Comment by nineinchnick** [comment]
I thought it's something with EOLs on Windows, but I get a different error with both \n and \r\n:
```
Invalid command \set SHOW_HOST_INFORMATION false. Try \? for help.
```
@mloskot can you create a new issue for this?

**Comment by mloskot** [comment]
> @mloskot can you create a new issue for this?

@nineinchnick Willingly, done.
