### ISSUE TITLE
retain query results

### ISSUE THREAD

**Issue by mckennagene** [xo/usql#274]
after a query runs, i see the results, then press a key and all the query results disappear. It seems to work the same as gnu's "less" tool. I can see some people might like that. But is there a switch i can set to keep the results visible in the terminal after the query completes? Similar to the -X flag that "less" has?

**Comment by mckennagene** [comment]
Answered my own question. I noticed it was literally using "less", not just imitating it. If you put export LESS="-x" in your .bashrc or .bash_profile, it works. Query results stay on screen after you quit out of the result viewer.

**Comment by kenshaw** [comment]
@mckennagene if you're familiar with `psql`, we have tried to imitate `psql` wherever possible, especially in things behaving like bash. It's not perfect, but is definitely much better using `usql` with every single database that isn't `psql` essentially. If you're not familiar with `psql`'s more advanced functionality, checkout variables. Here's my database creation script that I use for Oracle:

```
 usql
Type "help" for help.

(not connected)=> \c or://localhost/db1
Connected with driver oracle (Oracle Database 19.0.0.0.0)
or:system@localhost/db1=> \set NAME mytestdb
or:system@localhost/db1=> \set PASS mytestdb
or:system@localhost/db1=> \! cat init/oracle.sql
DROP TABLESPACE :NAME INCLUDING CONTENTS AND DATAFILES;

DROP USER :NAME CASCADE;

CREATE TABLESPACE :NAME NOLOGGING DATAFILE :'DATAFILE' SIZE 100M AUTOEXTEND ON;

CREATE
  USER :NAME
  IDENTIFIED BY :PASS
  DEFAULT TABLESPACE :NAME;

GRANT
  CONNECT,
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER,
  UNLIMITED TABLESPACE,
  SELECT ANY DICTIONARY
TO :NAME;
or:system@localhost/db1=> \set DATAFILE /opt/oracle/oradata/ORASID/mytestdb.dbf
or:system@localhost/db1=> \i init/oracle.sql
error: oracle: ORA-00959: tablespace 'MYTESTDB' does not exist
error: oracle: ORA-01918: user 'MYTESTDB' does not exist
CREATE TABLESPACE
CREATE USER
GRANT
error: init/oracle.sql: oracle: ORA-01918: user 'MYTESTDB' does not exist
or:system@localhost/db1=>
```

`usql` also has a `usqlpass` file (see the `README.md`).

**Comment by mckennagene** [comment]
I am a huge psql fan suddenly finding myself needing to be on Oracle. You
read my mind exactly. Spent a few hours today googling "psql with oracle"
and tried 3 other sql shells before I found usal.  It's great, thank you so
much.
