### ISSUE TITLE
proposal: execute queries in a file without trailing ;

### ISSUE THREAD

**Issue by mckennagene** [xo/usql#275]
minor convenience. 

I like to execute queries in a file on command line like
usql < myquery.sql > myquery.txt

This works, but only if the query in myquery.sql ends with a ;
In psql and others, it will interpret EOF as a ; and execute even without a trailing ;

this is a minor issue, obviously just adding a ; at the end gets around the issue

**Comment by kenshaw** [comment]
You can use either `\g` or `;` to terminate a query, or use the command-line option `-c` which automatically terminates a direct command. You can use/play with `/dev/stdin` and `/dev/stdout` if you need to effectuate this, and/or use a temporary file with the output:

```sh
$ usql -c "$(cat myquery.sql)" > myquery.txt
```
