### ISSUE TITLE
Not only output to csv, but input from csv too

### ISSUE THREAD

**Issue by calebeaires** [xo/usql#277]
After a look at readme.me I did not found a way to do input with the usql command line. this way I can output values

```bash
usql --csv my://user:password@123.123.123:3306/table?charset=utf8mb4,utf8  -w  --command "SELECT name, email from users limit 2"  > output.csv

```

but how to ?

```bash
usql --csv my://user:password@123.123.123:3306/table  -w  --command "insert into table base (....)"  < input.csv

```

**Comment by nineinchnick** [comment]
The readme suggest using the `csvq` driver for this:
>  Unlike psql, \copy in usql cannot read data directly from files. Drivers like csvq can help with this, since they support reading CSV and JSON files.

And there's an example:
```
$ cat books.csv
book_id,author_id,isbn,title,year,available,tags
3,1,3,one,2018,"2018-06-01 00:00:00",{}
4,2,4,two,2019,"2019-06-01 00:00:00",{}

$ usql -c "\copy csvq://. sqlite3://test.db 'select * from books' 'books'"
Copied 2 rows
```

**Comment by whutmacma** [comment]
cat books.csv |  usql -c "\copy  sqlite3://test.db 'select * from books' "

**Comment by whutmacma** [comment]
cat books.csv | usql -c "\copy sqlite3://test.db book(books,author_id,isbn,title,year,available,tags) from stdin"

How to?

**Comment by whutmacma** [comment]
cat books.csv | usql -c "\copy sqlite3://test.db book(books,author_id,isbn,title,year,available,tags) from stdin"

How to?
