### ISSUE TITLE
oracle SYSDBA

### ISSUE THREAD

**Issue by benor1470** [xo/usql#279]
Hi
I'm trying to run a query using SYS account and getting an error
when running
`usql.exe -f file.sql oracle://sys:password@server:1521/xe/`
I'm getting the error
error: oracle: ORA-28009: connection as SYS should be as SYSDBA or SYSOPER

in oracle sql cli tool logging in as sys user requires adding as SYSDBA in the connection string, but I can't find the syntax for it in usql

thank you

**Comment by kenshaw** [comment]
1. Parameters are injected using URL query values (see the `go-ora` driver itself, and the `dburl` documentation
2. Don't have a trailing slash after your SID

I'll look it up on the morning for you.

**Comment by kenshaw** [comment]
Using the `go-ora` driver, the `?DBA PRIVILEGE=` query parameter needs to be used.

You will need to url encode the space:

```sh
$ usql or://sys:P4ssw0rd@localhost/db1?DBA%20PRIVILEGE=sysdba
Connected with driver oracle (Oracle Database 19.0.0.0.0)
...
```

Alternately, pass it in a quoted string:

```sh
$ usql 'or://sys:P4ssw0rd@localhost/db1?DBA PRIVILEGE=sysdba'
Connected with driver oracle (Oracle Database 19.0.0.0.0)
...
```

Note: this also works for the `SYSOPER` DBA privilege.
