### ISSUE TITLE
Autocomplete MySQL specific keywords like USE <database>

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [xo/usql#285]
hi, i use mycli before, the code completion seems to be quick, can usql make the improvement of code completion?
great thanks for this amazing tool

**Comment by nineinchnick** [comment]
Completion in usql works differently than in mycli. What specific improvements do you have in mind?

**Comment by ziyouchutuwenwu** [comment]
thanks for your quick response.

1, wish to complete without tab pressed
2, drop down list seems to be much clear than flattern list. please theck the images
3, completion seems not working for some words. for example: use mysql, i input `us`, press tab, nothing happened. and i input `use m`, press tab, no completion. wish it can tell me the db started with `m`, such as `mysql`, etc.

images here

drop_down_list completion from mycli
![drop_down_list](https://user-images.githubusercontent.com/7458713/127666054-a48a83b7-06cd-4db0-9e93-1f9e34b6a449.png)


flatten_list completion from usql
![table](https://user-images.githubusercontent.com/7458713/127666131-2da02a13-e163-4471-af56-6923b132165c.png)

**Comment by nineinchnick** [comment]
1 and 2 depend on the particular readline library we're using and we cannot change this without replacing this whole library.

Right now we have a single completer that's enabled for all databases, so it doesn't recognize keywords that are only used by some of them. `USE` is a good example here. There is a possibility to configure a custom completer for each driver, so it can be extended to support some special keywords. Getting a list of databases in MySQL would be trivial, given there's already a metadata reader available that can list schemas.

If you don't mind, I'll edit the title of this issue to better reflect that this is mostly about MySQL.

**Comment by ziyouchutuwenwu** [comment]
thank you very much
