### ISSUE TITLE
USQL Installation instruction - GO GET is deprecated

### ISSUE THREAD

**Issue by mckennagene** [xo/usql#293]
The instructions for "Installing via Go" , include this statement,
$ GO111MODULE=on go get github.com/xo/usql

And similar like this for adding oracle go driver.
GO111MODULE=on go get -tags 'godror odbc' github.com/xo/usql

When these are run, a warning about 'get' deprecation is given. It's just a deprecation warning, so not critical today, one can ignore it. However at some point, presumably, this won't be supported. 

go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

Presumably one should instead do this command with "go install" and specify a version #, such as ....

GO111MODULE=on go install -tags 'godror odbc' github.com/xo/usql@latest

But this fails with an ERROR message about replace directives.

go install: github.com/xo/usql@latest (in github.com/xo/usql@v0.9.4):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

**Comment by jpy-git** [comment]
@mckennagene I'm having the same issue. I can install fine via `brew install xo/xo/usql` but that won't give me the Snowflake driver which I require. I tried the same as you with the same results.

My quick workaround for now was to clone the repo and build with my required tags:
`git clone https://github.com/xo/usql && cd usql && go build -tags="most snowflake" .`
Then I just moved the executable to `~/bin` which I've added to my path.

I'm no go expert so can't suggest a proper fix to get `go install` working but the above is good if you need the program quickly 😄

**Comment by kenshaw** [comment]
This works fine on my system with `go1.17.3`:
```
go install -tags most github.com/xo/usql@master
```

**Comment by kenshaw** [comment]
@jpg-git as I'm developing `usql`, I use the `most.sh` script to build and install locally:

```
$ cd /path/to/usql
$ ./most.sh -i -t godror -t snowflake
```

The above would install and additionally use the tags `godror` and `snowflake` in addition to the `most` tag.
