### ISSUE TITLE
CSV output has a trailing empty line

### ISSUE THREAD

**Issue by gumblex** [xo/usql#297]
I am exporting some tables to CSV with usql (0.9.4):
```
usql -c "SELECT * FROM table" -C -q -t -o result.csv oracle://...
```
The CSV output always has a trailing empty line, like "...field1,field2\nfield1,field2\n\n"
I must use `truncate -s -1 result.csv` before feeding into other tools.

**Comment by kenshaw** [comment]
Fixed with latest release, which will go out shortly.
