### ISSUE TITLE
H2 connection URL is not documented

### ISSUE THREAD

**Issue by aplatypus** [xo/usql#306]
I am running a H2 database instance on my PC for testing.  I'd like to connect with `usql` but the documented URL given with 

*  [h2go](https://github.com/jmrobles/h2go) 
   `h2://sa@localhost/testdb?mem=true`

I'm able to use the database from [dBeaver](https://dbeaver.io) database workbench tool with the JDBC URL:
  * `jdbc:h2:tcp://localhost/./test`
quite happily.  I'd like to use my prefered console SQL client `usql` to access the DB for test scripts, etc.

I've confirmed this versin of `usql` has a H2 driver with the `\drivers` command.  Different variants of the  [h2go](https://github.com/jmrobles/h2go)  H2 URL example like ...

```
 $ usql  jdbc:h2://localhost/./test
 $ usql  h2:jdbc://localhost/./test
 $ usql  h2:localhost://localhost/./test
 $ usql  h2:sa@localhost://localhost/./test
 $ usql  h2:tcp://sa@localhost:9092/./test
```

These examples usually return...

>  `error: h2: driver: bad connection`
> `error: h2: failed to open H2 connection: dial tcp: lookup tcp: no such host`

Essentially things are not getting the connection specifications right.  I can't find anything to show how this ought to work.  The server is started with this command.
* `java -jar h2/bin/h2-1.4.200.jar -webAllowOthers -tcpAllowOthers -ifNotExists`

I think exampe connection strings should be shown for the built in database types when they are added.  Ideally some explaination would be helpful too.

---- 
```
usql --version
usql 0.9.4

h2/bin/h2-1.4.200.jar
```

**Comment by kenshaw** [comment]
I'll test/verify later, but I believe the URL needed with usql is: h2://sa@localhost/test?mem=true

**Comment by aplatypus** [comment]
Thanks @kenshaw  ... Unfortunately, as I thought that URL familiar as one I used earlier; is a bust.
```
 $ usql  h2://sa@localhost/test?mem=true
/prod/tools/usql/usql h2://sa@localhost/test?mem=true
error: h2: driver: bad connection
```
I should note that I had to '_tune_' `dBeaver` before it worked for me.    I much wand a CLI interface as the main use case.

**Comment by kenshaw** [comment]
@aplatypus Using the `buildo/h2database` docker image, I was able to connect just fine with this: `usql h2://sa@localhost/testdb?mem=true`. Whether or not the `h2` driver _works_ properly or not is a separate issue. I'd try playing around with the Go driver directly, as fixing underlying Go drivers is not a goal for the `usql` project. If you're not able to connect, you might want to check which version of H2 you're working with, and if the TCP server is running on port 9092.

**Comment by aplatypus** [comment]
* Yes that's a memory database.
* The use case that isn't available is connecting to H2 as a server
* The use case in question is:
> `jdbc:h2:tcp://localhost/./test` 
    That connection string works with `DBeaver` workbench and using `Liquibase`.
* I just wanted to use `usql` because it has so far proven to be a very useful command line tool.

**Comment by kenshaw** [comment]
I'd suggest trying with some actual Go code then, and the H2 driver. I don't know how you have your H2 instance configured, and without a repeatable configuration, I can't help debug this. The h2 driver in use, and documentation is [available here](https://github.com/jmrobles/h2go).

**Comment by giamma** [comment]
The problem is in the driver itself that only supports in-memory H2, see https://github.com/jmrobles/h2go/issues/5 and https://github.com/xo/usql/issues/2

I believe H2 support should be removed from the documentation of USQL as users do not expect that only the in-memory database is supported because when using in-memory H2 you cannot connect to an external H2 server and you will loose all of your data when the USQL process is closed, so it's basically not usable for anything beyond an interactive playground.
