### ISSUE TITLE
converting NULL to uint32 is unsupported

### ISSUE THREAD

**Issue by srggavrilov** [xo/usql#307]
After upgrading from `0.9.0` to `0.9.5` I see the following error on `SHOW SLAVE STATUS`:
```
error: mysql: sql: Scan error on column index 43, name "SQL_Remaining_Delay": converting NULL to uint32 is unsupported
```

**Comment by kenshaw** [comment]
What version of MySQL are you using?

**Comment by srggavrilov** [comment]
MySQL Engine: `5.7.mysql_aurora.2.10.0`
Driver: `github.com/go-sql-driver/mysql v1.6.0`

**Comment by kenshaw** [comment]
Closing due to age. I tested this on a MySQL main/replica config and I am not seeing this issue.
