### ISSUE TITLE
Unable to set argument to PAGER

### ISSUE THREAD

**Issue by noborus** [xo/usql#308]
Commands with no arguments work
```
\set PAGER 'less'
```
But it doesn't work with arguments
```
\set PAGER 'less --header 1'
SELECT * FROM test;
error: pq: exec: "less --header 1": executable file not found in $PATH
```

It was an example using less, but I am developing a [pager](https://github.com/noborus/ov) and would like to specify many options to use it.
```
\set PAGER'ov -C -d "|" -H1 -F'
```

**Comment by nineinchnick** [comment]
As a workaround, can you try using an alias or creating a wrapper script?

**Comment by noborus** [comment]
Of course, workarounds are possible.
But I would like to show the user the best way to configure the pager.
I think it's better to just write one line in the config file.

**Comment by nineinchnick** [comment]
Sure, this is a valid issue/request, especially since it looks like `psql` allows to use a pager with arguments.

**Comment by noborus** [comment]
I sent a pull request to xo/tblfmt.
Please let me know if you have any problems.

**Comment by renard** [comment]
@noborus That is a great job. I did a very simple test and it looks good for me.

**Comment by kenshaw** [comment]
Please note that `less` has the `LESS` environment variable. This would have always worked by setting `LESS` in your shell environment.

```sh
$ export LESS='-S -I -R'
```

**Comment by Crissante** [comment]
I believe this should still be possible with usql as all other command line tools I've used respect setting flags in `PAGER`.

Is this possible @kenshaw?

**Comment by klardotsh** [comment]
This also just bit me when working with a SQLite database. This is the first tool I've ever seen that treats `$PAGER` as a raw value to look up in `$PATH` and does no sort of splitting or parsing. Yes, I *could* create wrapper scripts, but the behaviour still violates the principle of least surprise IMO.
