### ISSUE TITLE
Connection oracle error

### ISSUE THREAD

**Issue by JuchangGit** [xo/usql#310]
usql oracle://test:test@127.0.0.1:1521/lzdw
Connected with driver oracle (<unknown, error: oracle: ORA-00942: table or view does not exist>)
Type "help" for help.

or:lzuapp@202.201.13.24:40011/lzudw=>

**Comment by kenshaw** [comment]
What version of Oracle Database are you using?

**Comment by JuchangGit** [comment]
18c

**Comment by kenshaw** [comment]
It should work fine with 18c. Possibly your account doesn't have permission call `SELECT version FROM v$instance` which is what `usql` uses to determine the database version.
