### ISSUE TITLE
\watch should not use PAGER

### ISSUE THREAD

**Issue by noborus** [xo/usql#313]
Whenever a pager is used in \watch, the PAGER needs to be terminated manually.

If \watch wants to use the PAGER, `usql` will have to output to the pager (without exiting).
See PSQL_WATCH_PAGER in PostgreSQL15.

**Comment by nineinchnick** [comment]
Fixed in https://github.com/xo/usql/commit/f23d610fb57c040899b059d69ce94c1d15194e49
