### ISSUE TITLE
Oracle driver with error diffie hellman key exchange still under development

### ISSUE THREAD

**Issue by calebeaires** [xo/usql#314]
Version: go-ora v2.2.15
usql: v0.9.5
Go version: 1.16

While using [usql](https://github.com/xo/usql) to connect to oracle, the drive show this error

Usql command

```bash
usql or://pass:pass@localhost:1521/service
````

Returns

```bash
error: oracle: diffie hellman key exchange still under development
```

The go-ora documentation says to edit sqlnet.ora and add the following text. I did but I am guessing usql and oracle driver are not recognizing this custo settings. Do you folks has some clue on how to fix this.

```
# possible values ([accepted | rejected | requested | required])
SQLNET.CRYPTO_CHECKSUM_SERVER = required
# possible values ([MD5 | SHA1 | SHA256 | SHA384 | SHA512])
SQLNET.CRYPTO_CHECKSUM_TYPES_SERVER = SHA512
```

**Comment by kenshaw** [comment]
What database version are you using?

**Comment by kenshaw** [comment]
I just pushed a commit with the latest dependency updates, which included a bump for `go-ora`. If you're building `usql` from source, please pull the latest version and build/install and try again. Let me know if the issue persists. As this is an issue with the underlying database driver, there's not much that I'm able to fix in `usql` itself. Separately, if you'd prefer, there's also the `godror` driver that you could try using. The `godror` driver, however, requires building from source and having your environment setup/configured properly.

**Comment by calebeaires** [comment]
@kenshaw 
Oracle Database 11.2.0.4.0

After update to usql/master version, the driver still shows the save error Hellman message. I could use godror, but I am a bit confusing on where to place setup/config files. 

Right now, I set `sqlnet.ora` file at the folder `/opt/oracle/.../network/admin`, but I am guessing is not the right place to do it. Please, may you lead me to some documentation on how to make it done.

thanks

**Comment by kenshaw** [comment]
@calebeaires What OS are you using? Windows, macOS, ...? I'd be glad to help you with your config.

I've gotten the `godror` driver working on Windows, macOS, and Linux. I don't specifically recall the instructions for Windows, but for macOS/Linux it's more or less the same:

1. Download the Oracle instantclient SDK, and unpack to a regular directory
2. Create a `pkg-config` file (I believe it needs to be called`oci8.pc` for OCI
3. Make sure the location of the `oci8.pc` file is on your path.

Please take a look at the `contrib/godror/grab-instantclient.sh` in the `usql` sources, which is an automated script I use to setup/configure instantclient on Linux.

That script works with the following Oracle database versions:

```
21.1.0.0.0
19.9.0.0.0dbru
18.5.0.0.0dbru
12.2.0.1.0
```

Hope that can help you get going with `godror`. Happy to help if you run into other issues.

**Comment by kenshaw** [comment]
Also -- a point: Oracle 11 is now almost 10 years old (over??), and I've only ever tested `usql` using either `godror` or the other Oracle drivers against 12+. I realize it may not be possible for you, but I would highly suggest upgrading your database.

**Comment by calebeaires** [comment]
Hi @kenshaw,
It works now, but after I updated to the last version another issue came out: a table with 18.000 rows starts to deliver only 50 rows when exporting to CSV. 

There is no warning or erros at the terminal. I have tried do find out what make this happen, but I couldn't find exactly the bug.

**Comment by calebeaires** [comment]
@kenshaw,

Oracle Go Driver owner has answered this same question. This can give us a clue on how to fix it.

https://github.com/sijms/go-ora/issues/81#issuecomment-1049919320

**Comment by kenshaw** [comment]
@calebeaires I believe that we are buffering the data prior to displaying it. Could you share the schema and the query you're executing against? Likely this is some other issue with the syntax of a complicated query or some such, and not how `usql` is using the `ora` driver.
