### ISSUE TITLE
Hash comments not working in mysql driver

### ISSUE THREAD

**Issue by jpy-git** [xo/usql#318]
I'm currently connected to an amazon aurora db using the MySQL driver (`mysql://...`).

MySQL allows hash comments `# hello world` however when I try to execute a query containing one of these hash comments using usql it returns `EXEC`.

e.g.
```sql
# hello world
SELECT 1;
```
returns `EXEC`
```sql
-- hello world
SELECT 1;
```
returns 1

I've confirmed that the hash comments work fine when executing the query via PyCharm or SQLAlchemy so it seems to be a usql specific issue

**Comment by kenshaw** [comment]
Hash comment support is available on the MySQL drivers. This is an issue with `findPrefix`,  where it properly skips `--` comments and `/* */` comments. Will fix this shortly.
