### ISSUE TITLE
Provide option to customise usql prompt

### ISSUE THREAD

**Issue by jpy-git** [xo/usql#319]
Several of the DBs I work with have really long host names (it's pretty common with AWS/Azure) which results in my prompt in usql being unreasonably long causing a lot of wrapping and making queries quite hard to read.

Here's an example of how a simple query looks for me:
e.g.
```
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
ws.com:3306/some_db=> select foo
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
ws.com:3306/some_db-> from bar
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
my:datawarehouse@some-really-long-amazon-aurora-cluster-name-1234567.us-east-1.rds.amazona
ws.com:3306/some_db-> ;
```
n.b. When the prompt overflows the first part gets duplicated

It would be great if there was a config setting or environment variable to configure the prompt so it could be shorter.
Maybe could use the components described [here](https://github.com/xo/usql#:~:text=Where%20the%20above,path%20on%20disk) to generate it:
e.g. `\set CUSTOM_PROMPT driver/dbname` gives `my/some_db=>`
or `\set CUSTOM_PROMPT user:dbname` gives `datawarehouse:some_db=>`

Alternatively we could just set it directly (e.g. `\set CUSTOM_PROMPT myprompt` gives `myprompt=>`) but the solution above would still allow you to differentiate between different databases.

**Comment by kenshaw** [comment]
Yeah, this actually needs to be implemented for compatibility purposes with `psql`. It's not been high on my priority list, but would be a relatively easy/quick implementation. I'll try to see if I can get it done over the weekend, but I make no promises.

**Comment by d5ve** [comment]
I also work with very long AWS RDS hostnames, and made the following (hacky and fragile) change in [handler.go Prompt()](https://github.com/xo/usql/blob/cd6212718096ec78015fa2cb3e419bcbbe1034f8/handler/handler.go#L430) to reduce the hostnames to just the first portion.

`my:appuser@very-important-database.cluster-d34db33f.eu-west-1.rds.amazon.com/please_do_not_delete=>`
becomes
`my:appuser@very-important-database/please_do_not_delete=>`


```bash
diff --git a/handler/handler.go b/handler/handler.go
index ad8e287..55eb181 100644
--- a/handler/handler.go
+++ b/handler/handler.go
@@ -435,6 +435,9 @@ func (h *Handler) Prompt() string {
                        s = "(" + h.u.Driver + ")"
                }
        }
+       // Replace aaaa.bbbb.cccc.com with aaa.
+       var re = regexp.MustCompile(`@([^.]+)[^/]+/`)
+       s = re.ReplaceAllString(s, `@$1/`)
        tx := ">"
        if h.tx != nil || h.batch {
                tx = "~"
```

**Comment by d5ve** [comment]
Doh, I just noticed that the current database/schema name doesn't seem to be updated when I change databases in the client.

```sql
my:appuser@very-important-database/please_do_not_delete=> USE test_database;
USE
my:appuser@very-important-database/please_do_not_delete=>
```

**Comment by kenshaw** [comment]
I've pushed a commit that provides minimal implementation of this.

**Comment by exastone** [comment]
it would be a great help to accept color codes in the prompt. e.g.

`\set PROMPT1 \033[32m%S%m%/%R%#\033[0m`

**Comment by nineinchnick** [comment]
Support for this was added almost a year ago in https://github.com/xo/usql/pull/388. Is it not working for you? Can you create a new issue if so? This one's closed.

**Comment by exastone** [comment]
> Support for this was added almost a year ago in #388. Is it not working for you? Can you create a new issue if so? This one's closed.

you are right, I was in the process of editing the comment to make a note about requiring to use parentheses to as a hint to future users.

e.g.
`\set PROMPT1 "\033[32m%S%m%/%R%#\033[0m"` works
`\set PROMPT1 \033[32m%S%m%/%R%#\033[0m` does not

submitting a PR now with a one line update with an example in the .usqlrc section (setting custom prompt variable seems to missing from the docs)
