### ISSUE TITLE
[feature request] respect RFC 6761

### ISSUE THREAD

**Issue by CircleCode** [xo/usql#324]
it appears usql tries to resolve `foo.bar.localhost` through system resolver instead of transalting it into 127.0.0.1

**Comment by kenshaw** [comment]
`usql` uses the various Go SQL drivers. This is not an issue with `usql`.

**Comment by CircleCode** [comment]
thanks for the quick answer.
So to fully understand it and report my request to the correct project, I should report it to go-sql-driver/mysql, right?
