### ISSUE TITLE
[clickhouse]database component in DSN does not work

### ISSUE THREAD

**Issue by kilik52** [xo/usql#325]
version： usql-0.10.0-darwin-amd64.tar.bz2

see screen shot blew:

<img width="711" alt="截屏2022-04-15 上午10 24 22" src="https://user-images.githubusercontent.com/37238/163508531-68b3ab06-689c-4747-bca2-de52c0b7cc1c.png">

fail to find tables when add database name in connection string

**Comment by kilik52** [comment]
Addtional info
<img width="705" alt="截屏2022-04-15 上午10 41 38" src="https://user-images.githubusercontent.com/37238/163509551-2eb97705-f782-470f-b066-01a9c46cd360.png">

**Comment by kenshaw** [comment]
Fixed with `v0.12.13`. I'll be doing a release shortly.
