### ISSUE TITLE
Credentials from .usqlpass file are not used

### ISSUE THREAD

**Issue by usommerl** [xo/usql#326]
First of all thanks for this handy tool! I'm just playing around with it for an hour so maybe I'm just too dumb to use it and this isn't really a software problem. Here is my issue:

I'm using `usql` to connect to a [CockroachDB Serverless][1] instance and this is working fine when I provide the full connection string which includes the credentials:

```
usql 'cockroach://myuser:mypass@free-tier5.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dmycluster-3361'

Connected with driver postgres (PostgreSQL 13.0.0)
Type "help" for help.

cr:myuser@free-tier5.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb=>
```
What I really would like to do is to move the credentials in the `~/.usqlpass` file like so:

```
# format is:
# protocol:host:port:dbname:user:pass
cockroach:*:*:*:myuser:mypass
```

However, the client does not seem to pick up this information when I try to connect:

```
usql 'cockroach://myuser@free-tier5.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dmycluster-3361'
error: pq: 28000: password authentication failed for user myuser
```

Am I doing something wrong or is this a bug? Can I somehow check whether the `~/.usqlpass` file is read at all?

```
usql --version
usql 0.10.0
```

[1]: https://www.cockroachlabs.com/get-started-cockroachdb/

**Comment by kenshaw** [comment]
Try `cockroachdb`. If that doesn't work, just use the `postgres` name, as `cockroach` just uses the `postgres` connection.

**Comment by usommerl** [comment]
@kenshaw It works when I use `cockroachdb`. Thanks a lot!

I assumed that I can use any scheme alias in the `.usqlpass` file but that does not seem to be the case. Is there a general rule on which scheme identifier can be used in this file? Maybe the documentation could be improved in this regard?

**Comment by kenshaw** [comment]
It needs to be the primary name. I chose to do it that way for a number of reasons. The rule is that it can't be an alias on the `dburl` documentation.
