### ISSUE TITLE
feature request: tab completion on `\d` commands

### ISSUE THREAD

**Issue by mmisiewicz** [xo/usql#328]
It would be a big boost to productivity if tab completion worked on \d commands. In particular `\d <table>` is something that gets used all the time and it's a bit tricky to remember all the table names! 

For comparison, `psql` does this, so that would be the desired functionality to emulate.

**Comment by nineinchnick** [comment]
What database are you using?

**Comment by nineinchnick** [comment]
I checked and indeed we don't complete tables for these commands. But we do in select from statements, so it should be fairly easy to add.

**Comment by mmisiewicz** [comment]
I use both Postgres and Snowflake and haven't seen auto-completion working for either of those drivers, confirming your analysis!
