### ISSUE TITLE
能否增加几个数据库的支持

### ISSUE THREAD

**Issue by super-vip** [xo/usql#331]
能否增加对以下：达梦(dm),金仓(kingbase),神通(shentong),南大通用(gbase) 数据库的支持？
参考项目：https://gitee.com/chunanyong/zorm

**Comment by kenshaw** [comment]
@super-vip I am always open to adding support for more databases. I am not able to find the Go drivers for those databases. Could you provide links to any available Go driver for them? Thanks.

**Comment by kenshaw** [comment]
It appears that the Kingbase database is just based on PostgreSQL, so I would assume that the `postgres` driver works fine. The Shentong database appears to have ODBC drivers available, and no Go drivers available -- as such, you should be able to connect to it using the `odbc` driver. The Gbase database seems to be based on MySQL, and as such the `mysql` driver should work with it.

**Comment by super-vip** [comment]
@kenshaw 
Official Driver
[kingbase-v8r6_golang.zip](https://github.com/user-attachments/files/15812342/kingbase-v8r6_golang.zip)
[kingbase-v8r6_golang_x86_64.tar.gz](https://github.com/user-attachments/files/15812343/kingbase-v8r6_golang_x86_64.tar.gz)
[dm8-go-20240326.zip](https://github.com/user-attachments/files/15812344/dm8-go-20240326.zip)

**Comment by kenshaw** [comment]
@super-vip Thanks for sharing this example, however these drivers don't seem to be available on the website. As such, I do not intend on supporting them, unless they are publicly available. Understand that if they're not publicly available, it creates extreme problems in getting Go to compile out of the box, and I personally don't have the time to create/support yet another repository. If you work with the Kingbase team, perhaps you can convince them to make these available in a more conventional Go way, such as hosting it here on GitHub.com.

**Comment by super-vip** [comment]
Received, I understand. Nevertheless, thank you for your attention and prompt reply.
