### ISSUE TITLE
Problem with installing oracle driver

### ISSUE THREAD

**Issue by asayamakk** [xo/usql#35]
I installed usql with command 
`$ go get -u -tags 'oracle odbc' github.com/xo/usql`

It looks successfully installed and works fine with mysql.

```
$ usql mysql://tmp:tmp@localhost:3306
Connected with driver mysql (5.7.20-log)
Type "help" for help.

my:tmp@localhost:3306=> ^D
```

however when i tried to connect to oracle databases, i got following error message

```
$ usql oracle://test@127.0.0.1:1521/tdb
error: ora: driver not available

try:

  go get -u -tags oracle github.com/knq/usql

```

my environments

```
OS: Mac OS 10.11
go: go1.8.3 darwin/amd64
```

```
cat oci8.pc
prefix=/Users/usr0200557/bin/oracle-sdk/instantclient_11_2
libdir=${prefix}
includedir=${prefix}/sdk/include/

Name: oci8
Description: Oracle Instant Client
Version: 11.2
Libs: -L${libdir} -lclntsh
Libs.private:
Cflags: -I${includedir}
```

Thank you for reading!

**Comment by kenshaw** [comment]
You likely have a configuration problem with `$PATH`: note that the text in the issue you posted is 

`go get -u -tags oracle github.com/knq/usql` 

This is the old version before the project moved to its current location. If you look at `main.go` you can see that this path has been updated to the most recent location. My guess is that you have multiple locations that you previously built (or installed) `usql` at that is masking/overriding the new version. You can figure this out by doing:

```sh
$ which usql
```

If that's not the same as `$GOPATH/bin`, then what I described above is the problem. You can check what Go sees as `$GOPATH` by doing the following:

```sh
$ go env GOPATH
```

It's worth noting that I have put out [homebrew verisons of `usql`](https://github.com/xo/homebrew-xo/):

It might be easier for you to install `usql` using that: 

```sh
# add homebrew tap
$ brew tap xo/xo

# install usql with "most" drivers
$ brew install usql

# install xo with oracle support
$ brew install --with-oracle xo

# install usql with oracle and odbc support
$ brew install --with-oracle --with-odbc usql
```

**Comment by asayamakk** [comment]
Thanks for replying and solution.

As you said, i was exuceting wrong usql command.
Now I can use usql with oracle database. and I'm so happy that usql is amazing compared to sql*plus!!

thank you :)
