### ISSUE TITLE
[Feature Request] Output as json

### ISSUE THREAD

**Issue by mtxr** [xo/usql#37]
Is it possible to output rowsets as json instead of a table?

It would be useful when running cli statements piping to other commands.

**Comment by eadmaster** [comment]
I second the request. I've found [this alternative that requires docker](https://github.com/function61/sql2json/).

csv export would be useful as well.

**Comment by kenshaw** [comment]
This is definitely coming, but I don't have a specific ETA -- I don't really have the amount of time I'd like to commit to this project, even though `usql` is about my favorite project! I recently took the time to write the `tblfmt` package from scratch, in anticipation of doing more formatting export, and to be compatible with `psql`. There really isn't *too* much work necessary to get `usql` the rest of the way there, but it is *time-consuming* work. I'm hoping before end of 2018 that `usql` will be 100% compatible / feature-complete with `psql` and support even more features than it. PRs would be greatly appreciated!

**Comment by nineinchnick** [comment]
Looks like both CSV and JSON are already implemented, just with minor issues with processing `-C` and `-J` flags in 0.7.8. These issues are already resolved on master.

As a workaround, `-P format=json` can be used. See #124
