### ISSUE TITLE
usql with oauth

### ISSUE THREAD

**Issue by ghost** [xo/usql#377]
Hi everyone.

#### idea
I was thinking of adding a web interface to authenticate the database in usql. So would use [OAuth](https://github.com/go-oauth2/oauth2) from those services to kick-off your local config.

#### concept
```javascript
$ usql --postgress --oauth
 - $ pg://user:pass@host/dbname
```

#### idea
![image](https://user-images.githubusercontent.com/111701513/194709566-7a680fe9-a939-45b5-b1fc-bd22848f0794.png)

#### note/license
this idea(ui) is based on [Devzstudio/Web3UIKit](https://github.com/Devzstudio/Web3UIKit).

**Comment by nineinchnick** [comment]
Do you want `usql` to start a web server? I don't think that's a good idea. Instead, I'd suggest opening a browser whenever needed to complete an OAuth workflow. But I'm not aware of any Go SQL driver that would support it. Can you provide an example driver? Both `lib/pq` and `jacks/pgx` that we use for PostgreSQL don't support OAuth (yet).

**Comment by nineinchnick** [comment]
Thanks, that's a much better description of the request.

To avoid adding new flags, maybe this could be implemented as a new schema with a wrapped driver, something like `postgres+oauth://`. @kenshaw WDYT?

**Comment by kenshaw** [comment]
There's a database that requires oauth? How would that information even propagate from the database driver up to `usql`? I'm open for any PRs, as always.
