### ISSUE TITLE
Document all supported environment variables in README

### ISSUE THREAD

**Issue by nineinchnick** [xo/usql#379]
`usql` recognizes a few environmental variables, like:
* `PAGER`
* `EDITOR`
* `SHOW_HOST_INFORMATION`
* `QUIET`
* `ON_ERROR_STOP`

only some of them are documented. Add a new section in the README file.

**Comment by sfc-gh-pbennes** [comment]
Somewhere around https://github.com/xo/usql#backslash-commands seems like a reasonable place for such a section.

Also worth noting that `\? options` and `\? variables` appear in the documentation and interactive help (`\?`) but don't appear to work (same with options):

```
(not connected)=> \? variables
...
\?: extra argument "variables" ignored
```
