### ISSUE TITLE
wrapper driver that live outside of usql

### ISSUE THREAD

**Issue by ghost** [xo/usql#385]
Hi everyone.

I was thinking about usql having support for network protocol like IPFS, remote-storage, solid-project. 

*What do you all think of this idea?*

**Comment by nineinchnick** [comment]
usql only works with the `database/sql` Go API. Do you know about drivers for these networks that implement this API?

This is somehow related to #55 and #157

**Comment by nineinchnick** [comment]
How would you query these networks, if they don't support SQL? Maybe developing a wrapper driver that'd live outside of usql would make sense. Something similar to `csvq` that's responsible for parsing and executing SQL queries.
