### ISSUE TITLE
usql and git-bug?

### ISSUE THREAD

**Issue by codehangen** [xo/usql#386]
Hi all.

#### 1. concept
1. I want to know what you all think about the idea of using usql as a backend for git-bug. 
2. I would like to talk here about a killer application that could promote usql that would be git-bug. I believe that both projects have points in common: distribution, data/platform decentralization.

#### 2. context
1. "You would not need to rely on one or more issue and database vendors with git-bug and usql."
3. "Lately protocols like IPFS, Matrix, ActivityPub have been popular... part of that is that they are federated protocols. I believe git-bug could benefit from usql."
4. "We can use usql as a technical specification about a synchronization protocol, mirroring, sharing databases like matrix."
5. "We can use git-bug as a technical specification about a synchronization protocol, mirroring, sharing for issues like matrix."

#### 3. feedback/question
- *wdyt (what do you all think about the idea?)?*
- Have you all thought about providing a usql technical specification like matrix?

**Comment by nineinchnick** [comment]
I don't understand at all how usql which is a CLI client for multiple databases is related to git-bug which is an issue tracker. I can't think of any reasons to integrate these two apps and I don't see them in the issue description here either.
