### ISSUE TITLE
go mod has error

### ISSUE THREAD

**Issue by hantmac** [xo/usql#389]
I fork the code and execute `go get ./...` but got an error:

```
github.com/IBM/nzgo/v14: cannot find module providing package github.com/IBM/nzgo/v14
```

And I can not find the module `github.com/IBM/nzgo/v14` in project `github.com/IBM/nzgo` but I found `github.com/IBM/nzgo/v12` instead.

**Comment by kenshaw** [comment]
I believe this is due to using an older version of Go. Closing this issue, as I have no issues with v14 of the driver.

**Comment by hantmac** [comment]
> I believe this is due to using an older version of Go. Closing this issue, as I have no issues with v14 of the driver.

But I have not found the v14 driver in [this repo](github.com/IBM/nzgo).

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/7600925/210729055-2133dd2c-3b2d-410b-8055-dcdb9db7d459.png">

**Comment by hantmac** [comment]
@kenshaw The newest version of it is v12. Where is the 'v14' module?

**Comment by nineinchnick** [comment]
Maybe the maintainers have published it by mistake and deleted it but it got cached? BTW [the docs page](https://pkg.go.dev/github.com/IBM/nzgo?tab=versions) still shows both v12 and v14.

**Comment by nineinchnick** [comment]
Also these work:
```bash
% go list -m --versions github.com/IBM/nzgo/v14
github.com/IBM/nzgo/v14 v14.0.0
% go list -m --versions github.com/IBM/nzgo/v12
github.com/IBM/nzgo/v12 v12.0.1 v12.0.3 v12.0.5 v12.0.6 v12.0.7 v12.0.8
```

**Comment by hantmac** [comment]
It got cached. I clone the code and can not found the module.

```
❯ go get ./...
go: github.com/IBM/nzgo/v14@v14.0.0: reading https://goproxy.io/github.com/%21i%21b%21m/nzgo/v14/@v/v14.0.0.mod: 404 Not Found
        server response: not found: github.com/IBM/nzgo/v14@v14.0.0: invalid version: unknown revision v14.0.0
❯ go list -m --versions github.com/IBM/nzgo/v14
go: github.com/IBM/nzgo/v14@v14.0.0: reading https://goproxy.io/github.com/%21i%21b%21m/nzgo/v14/@v/v14.0.0.info: 404 Not Found
        server response: not found: github.com/IBM/nzgo/v14@v14.0.0: invalid version: unknown revision v14.0.0

```

**Comment by hantmac** [comment]
From [the docs page](https://pkg.go.dev/github.com/IBM/nzgo?tab=versions) the highest tagged major version is [v121](https://pkg.go.dev/github.com/IBM/nzgo/v121). How about  upgrade it to v121?

**Comment by hantmac** [comment]
> Maybe the maintainers have published it by mistake and deleted it but it got cached? BTW [the docs page](https://pkg.go.dev/github.com/IBM/nzgo?tab=versions) still shows both v12 and v14.

The v14 and v121 shown in [the docs page](https://pkg.go.dev/github.com/IBM/nzgo?tab=versions) might have problems and can't be used.

**Comment by kenshaw** [comment]
Honestly, if they can't tag things properly, I'm happy to just move it to the `bad` drivers and be done with it. @hantmac you might want to file a ticket on their page to let them know that [they can retract](https://go.dev/ref/mod#go-mod-file-retract) versions by publishing proper `go.mod` files.

**Comment by hantmac** [comment]
@kenshaw I have opened an issue but I found the repo is not so active. Maybe we should use v12 instead 🤔.

**Comment by kenshaw** [comment]
@hantmac if it's unmaintained, then it should definitely not be used in `usql` if it doesn't work "out of the box".

**Comment by hantmac** [comment]
> @hantmac if it's unmaintained, then it should definitely not be used in `usql` if it doesn't work "out of the box".

Make sense.

**Comment by hantmac** [comment]
This issue has not been fixed, how about reopen it?
