### ISSUE TITLE
`\d` returns incorrect foreign key constraint

### ISSUE THREAD

**Issue by notramo** [xo/usql#392]
The `\d <table_name>` command returns incorrect foreign key constraint on MariaDB (not tested other database systems).

The output says the foreign key references the table it is in.
E.g. there are `companies` and `employees` each employee has a `company_id` which is a foreign key index on `companies(id)`, but `usql` incorrectly shows in `\d employees` that it's on `employees(id)`.

**Comment by nineinchnick** [comment]
Thanks for reporting this. Can you include a full table schema (CREATE TABLE statements) and the output of `\d companies` and `\d employees`?

**Comment by notramo** [comment]
This is a minimal database, only the fields needed for reproducing this bug.
I noticed that if the foreign key constraint is created on a database that doesn't have a column with the referenced column name (e.g. the foreign key constraint references the `id` column of the other table, but there is no `id` column in the current table), the result in the `\d` command output is `()`.
In the first example, there is only the `company_id` field in the `employees` table, so the last line of the output shows `()` after the `REFERENCES` statement (last line on the screenshot).


![image](https://user-images.githubusercontent.com/26059643/215345090-e9b10644-e27a-4295-b02b-f7f261338075.png)

After adding an `id` column to `employees`, it will show it as `employees(id)`.


![image](https://user-images.githubusercontent.com/26059643/215345677-f3151b20-0b02-4120-b5c6-aade436adb68.png)

**Comment by nineinchnick** [comment]
Thanks for all the details. There was an obvious bug and we were missing tests for MySQL.
