### ISSUE TITLE
Add support for "all" drivers in packaged releases

### ISSUE THREAD

**Issue by naclander** [xo/usql#40]
The release page contains links to ready made releases of usql ( which is awesome ) however they do not contain all drivers, namely Oracle. 

This was only tested on the linux tar.bz2 file, but I suspect the osx version is the same. Please update the binary releases so that they contain all drivers.

P.S. Thanks for the awesome program, I'm looking forward to using it.

**Comment by kenshaw** [comment]
This isn't possible, due to legal issues surrounding the Oracle drivers. The Oracle driver depends on the C lib published by Oracle, and it cannot be redistributed as part of a built binary.
