### ISSUE TITLE
Feature request: sslmode=disable hint

### ISSUE THREAD

**Issue by hissssst** [xo/usql#406]
Instead of writing this

```
error: pq: SSL is not enabled on the server
```

It would be nice to have something like this
```
error: pq: SSL is not enabled on the server

  hint: Try adding ?sslmode=disable to the connection uri
```

**Comment by kenshaw** [comment]
@hissssst The last tagged release includes an auto-retry for PostgreSQL connections with the `lib/pq`. What version are you on?

**Comment by kenshaw** [comment]
@hissssst that said, your request is 100% reasonable, and I'll make a point of adding that output with that error.

**Comment by hissssst** [comment]
I am on `usql 0.13.12`

**Comment by kenshaw** [comment]
`v0.14.0` added the change.
