### ISSUE TITLE
Default USQL prompt font color(white) clash with default macos terminal default(white) background.

### ISSUE THREAD

**Issue by quazirfangenus** [xo/usql#410]
Default font color is white for USQL prompt. Default background color of macos terminal is also white.

In this setup, user can not read what they are typing unless they hit space.

**Comment by kenshaw** [comment]
Try disabling syntax highlighting, or changing the theme. You likely are using a light background on macOS and not the "default background". In both iTerm2 and macOS' default Terminal app, the background color is black (I just checked on my Mac).

**Comment by quazirfangenus** [comment]
I found the solution. Just reporting it in case people think something else is wrong.

I think the default macos terminal background color depends on the theme you are on. The default macos theme is 'Light' which set the terminal background color to white.
