### ISSUE TITLE
2 security vendors and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by m2acgi** [xo/usql#413]
![2023-05-19_13-39-36_chrome](https://github.com/xo/usql/assets/34497122/aa465759-41db-40a3-8ccf-4ba922b4f3c2)
![2023-05-19_13-40-11_chrome](https://github.com/xo/usql/assets/34497122/8faa99c5-fe2f-490a-984d-9c67344226db)

**Comment by kenshaw** [comment]
This is not a security issue, and has happened before. Every Go app gets flagged the same way.
