### ISSUE TITLE
Support for NO_COLOR env variable

### ISSUE THREAD

**Issue by mil** [xo/usql#416]
Would be nice to support the NO_COLOR env variable. Would a patch for this be accepted?

Currently the variable SYNTAX_HL can be set to false as `\set SYNTAX_HL false` upon entering usql; but would be nice to have the `NO_COLOR` env variable set and respected.

https://no-color.org/

**Comment by kenshaw** [comment]
Yeah, sure this would be fine. I'll add it when I have a chance.
