### ISSUE TITLE
Feature: Saving query string to output files

### ISSUE THREAD

**Issue by cyberdummy** [xo/usql#430]
In my local version of usql I have added new Backslash Commands that will print the query string above the output since I find this helpful for output files.

They are like:
```
  \GQ [(OPTIONS)] [FILE]               as \G, but prints the query above results
  \gq [(OPTIONS)] [FILE]               as \g, but prints the query above results

  \oq FILE                             as \o, but print the queries also
```

Example:
```
my:root@localhost/test=> \oq output.txt
my:root@localhost/test=> select * from foo;
my:root@localhost/test=> select * from bar;
my:root@localhost/test=> quit

$ cat output.txt
select * from foo;
 name
-------
 barry
 jim
(2 rows)

select * from bar;
 fruit
-------
 apple
(1 row)

```

I can create a PR if there is any interest.

**Comment by kenshaw** [comment]
`psql` has functionality that supports this:

```sh
$ psql --echo-all -c 'select 1' postgres://postgres:P4ssw0rd@localhost/
\encoding utf8
select 1
 ?column? 
----------
        1
(1 row)
```

As such, I would prefer any PR to implement this functionality similarly for `usql`, as I am trying to adhere mostly to the existing `psql` conventions where possible.

**Comment by cyberdummy** [comment]
My understanding of that was it was just going to STDOUT not to a specified file in the blackslash command?

**Comment by kenshaw** [comment]
I'm not exactly sure what your use case for this kind of functionality would be for? I'm open to innovating with `usql`, but I believe part of why `psql` (and in turn `usql`) have been successful is that it fits into the "Unix" paradigm of do one thing well, and pass on output to additional tools. 

I think what you're wanting here is to be able to log all the queries and output during an interactive session. In my humble opinion, this is not really how `psql` is meant to be used -- that said, it is not my place how to tell people how to use their tools. 

I'm just sharing here how I use `usql` and how I think others use it: essentially, I don't use `usql` (or `psql` either) for making direct changes to databases, only for making some small ad-hoc queries or quickly querying things. For anything more complex than a simple `select * from <table> limit ...` style query, I always edit a separate file/script, and then executed it using that database's native SQL client (or `usql` when it makes sense to do so).

As you might be able to understand, the `--echo-all` kind of functionality is the kind of functionality that I would use/need/prefer in `usql`, as there are times that capturing the executed queries during a script run is useful, for example when trying to trace / debug a script in a log.

As in many things, I think the way that `psql` does it is extremely graceful. There is a global variable `ECHO` in `psql` that gets set:

```
postgres=# \set
...
ECHO = 'all'
...
```

And as such, if similar functionality is going to be added to `usql`, I think it wise to try to follow this.

**Comment by cyberdummy** [comment]
Gotcha, yes I use it differently mostly to quickly share queries / result sets with others without needing to create scripts.
Thanks!

**Comment by kenshaw** [comment]
@cyberdummy I would like to accommodate your use case, I just don't think that separate / duplicated meta commands is the right way.

**Comment by cyberdummy** [comment]
Appreciate that. You have made me think I should go about it a different way, so going to take a look at my workflow.

Here is how I currently do it:

Request comes in for some report based on DB data I will open `usql` and use `\e` (or just type it out but lets say `\e` for the example) to start creating and testing queries. Here is problem 1: I end up with a scrollback that I can not easily see / reference

```
my:root@localhost/test=> \e
 name
-------
 barry
(1 row)

my:root@localhost/test=> \e
 name
------
 jim
(1 row)

my:root@localhost/test=> \e
 fruit
-------
 apple
(1 row)
```

Change that to `\gq` I can see I more complete history

```
my:root@localhost/test=> \e
select * from bar
 fruit
-------
 apple
(1 row)

my:root@localhost/test=> \e
select * from foo limit 1
 name
-------
 barry
(1 row)
```

As you said the echo thing would actually solve this issue.

Problem 2 of this is sharing the output with others. What I usually send them is the query followed by the results so they can see the results and take the query to modify for themselves and there is some back and forth here. For that I can use the `\gq <file.txt>` and have a file ready to send with query + results.
Of course I could do extra steps like `\w <query.txt>` and then concat them together I am just being lazy.

Problem 3 is there is some discrepancy between 2 queries for example and I want to get another opinion on it here I use `\oq <file.txt>` run the 2 queries and send. Again all possible for the none lazy.

--

The way forward is probably to take this out of usql interactive and build some basic tooling to easily iterate on a query and create result set files and just call usql with the options like `-c`, `-f` & `-o`.

**Comment by kenshaw** [comment]
If you were not aware, there is the `\p` and the `\raw` meta commands:

```
$ usql pg://
Connected with driver postgres (PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1))
Type "help" for help.

pg:postgres@=> \e
 ?column? 
----------
        1 
(1 row)

pg:postgres@=> \p
select 1;
pg:postgres@=>  

```

If you have used `\e`, then your editor can save to a separate file (either from within the editor, or otherwise):

```
$ usql pg://
Connected with driver postgres (PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1))
Type "help" for help.

pg:postgres@=> \e test.sql
pg:postgres@-> \p
select 'my really cool string'
pg:postgres@-> \raw
select 'my really cool string'
pg:postgres@-> \echo `cat test.sql`
select 'my really cool string'
pg:postgres@-> 
```

**Comment by kenshaw** [comment]
Additionally:

```
pg:postgres@=> \e test.sql
       ?column?        
-----------------------
 my really cool string 
(1 row)

pg:postgres@=> \i test.sql
       ?column?        
-----------------------
 my really cool string 
(1 row)

pg:postgres@=> \echo `cat test.sql`
select 'my really cool string';
pg:postgres@=>  

```

**Comment by kenshaw** [comment]
Oops, sorry one more, in case you weren't aware:

```
pg:postgres@=> \! cat test.sql
select 'my really cool string';
pg:postgres@=>  
```

**Comment by cyberdummy** [comment]
Yup thanks, going some thing like `\e` then
```
select 'hello'
\p
\g
```
is pretty handy.
