### ISSUE TITLE
Is there any plan to support parquet or orc format?

### ISSUE THREAD

**Issue by lij55** [xo/usql#433]
usql is a good tool for data migration and I used it a lot! Thanks for the great job.

Parquet and orc has embedded schema information and better compression rate compared with csv and json. they can be 'queried' by sql as well (https://github.com/apache/arrow, https://github.com/apache/arrow-datafusion)

could usql support parquet as a source and target?

**Comment by kenshaw** [comment]
I believe DuckDB supports parquet file, as such I think `usql` already supports it?

**Comment by lij55** [comment]
yeah, seems so...thanks. let me try it.
