### ISSUE TITLE
error csv upload with pgx driver (encode date column)

### ISSUE THREAD

**Issue by artemklevtsov** [xo/usql#435]
Hi,

I faced with problem when tried to upload CSV using `pgx` driver. `postgres` driver is ok.

To reproduce:

```bash
printf "col1,col2\n2020-01-01,0\n" > test.csv

docker run --rm --detach --name pg -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:alpine

PGX_DSN="pgx://postgres:postgres@localhost:5432/postgres"
PG_DSN="postgres://postgres:postgres@localhost:5432/postgres"

usql --command "CREATE TABLE test(col1 date, col2 int)" "${PGX_DSN}"

usql --set="dsn=${PGX_DSN}" --command "\copy csvq://. :dsn 'SELECT * FROM test' 'test'"
usql --set="dsn=${PG_DSN}" --command "\copy csvq://. :dsn 'SELECT * FROM test' 'test'"

docker stop pg
```

Results:

```bash
usql --set="dsn=${PGX_DSN}" --command "\copy csvq://. :dsn 'SELECT * FROM test' 'test'"
# error: ERROR: COPY from stdin failed: unable to encode (*interface {})(0xc001b14a00) into binary format for date (OID 1082): cannot find encode plan (SQLSTATE 57014)
usql --set="dsn=${PG_DSN}" --command "\copy csvq://. :dsn 'SELECT * FROM test' 'test'"
# COPY 1
```

**Comment by nineinchnick** [comment]
Note, you have to use the `csvq` driver's syntax, not PostgreSQL's.

**Comment by nineinchnick** [comment]
If a driver can't return data in a format another driver would understand, that's a limitation of the driver, not `usql`.

**Comment by nineinchnick** [comment]
You should cast it to a date, not string/text/varchar.

**Comment by artemklevtsov** [comment]
I understand, but csvq don't support date type. Cast to `DATETIME` also don't work.
Can you show a correct query based on my example?

**Comment by nineinchnick** [comment]
So you'd have to copy the data into another table and do the conversion in PostgreSQL as a next step. But I'd recommend using PostgreSQL native tools for reading the CSV.

**Comment by kenshaw** [comment]
Also -- PostgreSQL natively supports importing CSVs using their `COPY` instruction. If you expose the file to a place where the server can see it, you should be able to use that command cleanly with `usql`.

**Comment by artemklevtsov** [comment]
Thanks for the replies.
I tried to switch from the `psql`. I want to use one cli tool for all operations for the most dbs.
Upload directly on server is not possible in my cases.
Now I can use `usql` witn `postgres` driver anyway.
