### ISSUE TITLE
Is terminal graphics in WezTerm under Windows supposed to work?

### ISSUE THREAD

**Issue by captainkirkoff** [xo/usql#442]
Hi,
trying to enable terminal graphics in wezterm with Windows 10.

![image](https://github.com/xo/usql/assets/6802846/b030b373-fa59-4f50-aa82-42e5167bc74f)

No logo displayed at the start of the interactive session.
Done several attempts: cmd (both with clink enabled and in pure native mode), powershell, WSL.

Moreover, syntax highlighting is only working in WSL, does not work in native Windows.

**Comment by kenshaw** [comment]
`TERM_GRAPHICS` is temporarily disabled by default, until an upcoming major release that will include charts. However, for `iTerm` and `Kitty` graphics, you will need to explicitly enable it using the `TERM_GRAPHICS` environment variable:

```sh
export TERM_GRAPHICS=iterm
```

WezTerm uses `iterm` graphics, so the above is what you will need to add to your environment. Those who use Sixel graphics should have it detected automatically, and enabled.
