### ISSUE TITLE
version 0.17.5 quit sliently on windows 7

### ISSUE THREAD

**Issue by l1t1** [xo/usql#447]
I test the 0.17.5 version, it also quit on windows 7, version 0.17.0 still works

D:>usql175 --version

D:>usql170 --version
usql 0.17.0

**Comment by kenshaw** [comment]
Windows 7 is no longer a supported platform. If you need to continue using `usql` on Windows 7, please continue with the older version. Alternately, please try the latest release (`v0.18.1`) to see if this works for you.
