### ISSUE TITLE
defining a variable and using it inside the script

### ISSUE THREAD

**Issue by kishorerathi** [xo/usql#45]
I have a SQL script which I want to run using usql. The script runs a query where a comparison value for a condition should be user supplied like
  
select * from listing where city = 'someUSERsuppliedValue'

A preferred approach will be to have a variable defined at the command line and use the variable  in the script.

How can I accomplish this in usql?

Appreciate the  help very much

**Comment by kenshaw** [comment]
```sh
$ ./usql booktest.sqlite3 
Connected with driver sqlite3 (SQLite3 3.21.0)
Type "help" for help.

sq:booktest.sqlite3=> \prompt myvar 'name: '
name: test
sq:booktest.sqlite3=> select * from authors where name = ':myvar';
  author_id | name  
+-----------+------+
(0 rows)

sq:booktest.sqlite3=> 
```

**Comment by kenshaw** [comment]
It's the same syntax as in `psql`. `':var'` to inject a single quoted var, or `":var"` to inject a double quoted var, or `:var` for a plain var.

**Comment by kishorerathi** [comment]
Thanks for the quick response. It worked
