### ISSUE TITLE
connect to clickhouse over http from cmdline

### ISSUE THREAD

**Issue by tarasglek** [xo/usql#463]
Hi, the clickhouse driver supports native and http. I can't figure out how to connect to clickhouse over http using usql.

The following works inside usql
```
\c clickhouse https://user:pass@host/db?secure
```

Why I can't a pass this as a param on cmdline? 

```
usql clickhouse:https://user:pass@host/db?secure
error: clickhouse: dial tcp: lookup https: no such host
```

 or 

```bash
usql clickhouse+https://user:pass@host/db?secure
error: invalid transport protocol
```
Neither works. Where am I getting the syntax wrong?

**Comment by kenshaw** [comment]
I've read the Clickhouse driver code, this needs to be added via `dburl` generating the schema with a `+http` and `+https` scheme. Alternately, could use completely different schemes. I'll look into this and try to get an implementation out in the next few hours.

**Comment by kenshaw** [comment]
Pushing a release now -- Clickhouse URLs should now support `clickhouse+http` and `clickhouse+https`. I have not thoroughly vetted this, please provide feedback if this meets your expectations.

**Comment by kenshaw** [comment]
@tarasglek I was just rereading your original comment. The commit I pushed adds support for `clickhouse+http://` and `clickhouse+https://` as URL schemes, however it's worth noting that `\c clickhouse https://user:pass@host/db?secure` should have been able to connect.

I would assume if it failed, you were on an older version of `usql` -- if so, could you share what version of `usql` you encountered this with?

Regardless, as soon as the builds have finished, I'll set the release and when you update to the latest `v0.19.1` version of `usql`, all of the URL forms you shared above should work. If they don't, please open a new issue and I'll debug further.

**Comment by tarasglek** [comment]
Wow, thanks for quick turn-around, I wish I reported this earlier :)
