### ISSUE TITLE
error: sqlserver: TLS Handshake failed: tls: server selected unsupported protocol version 301

### ISSUE THREAD

**Issue by CallmeprofessorDuan** [xo/usql#465]
Hi,
I encountered an error when connecting to the SQL Server database as follows
"error: sqlserver: TLS Handshake failed: tls: server selected unsupported protocol version 301"
Is there any way to solve it?

**Comment by kenshaw** [comment]
Per this [stackoverflow post](https://stackoverflow.com/questions/72327173/golang-err-tls-handshake-failed-tls-server-selected-unsupported-protocol-ve) you either need to uprade your SQL server connection, or disable encryption. Try adding a query string parameter `?encrypt=disable` to the URL and try again.

Closing this ticket as done, please reopen if this doesn't work for you.
