### ISSUE TITLE
USQL Databricks driver fails when connection with Azure Databricks

### ISSUE THREAD

**Issue by calebeaires** [xo/usql#466]
I am facing an issue when trying to connect to Databricks using ﻿usql. Even when using the correct credentials, typing the command:

```bash
usql databricks://token:dapi*****@adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******

```
The credentials and URL details have been omitted for security, but I assure you that the data is correct.

Error Logs:

![CleanShot 2024-06-05 at 10 28 57@2x](https://github.com/databricks/databricks-sql-go/assets/794195/ca61b967-1288-4ca3-b4e6-7872cf1500c2)

### What You Have Tried

- Verified credentials and URLs.
- Reinstalled ﻿usql.
- Tried on different terminals and operating systems (MacOS and Linux).

### Where it works

Using DBeaver and the same credentials, the connection works like a charm

Any help to resolve this issue would be highly appreciated.

**Comment by kenshaw** [comment]
@calebeaires this is likely due to how the URL is generated for the driver. I had based this on the reference code for AWS. Specifically, the URL is bad. Could you try opening an interactive interpreter session, and then doing this:

```sh
$ usql
(not connected)=> \c databricks token:dapi*****@adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******
```

The issue is that the path generated from `dburl` is incorrect for Azure. 

I will think about the best way to handle this in the future, but you should be able to connect using the direct connection syntax (see above's `\c`).

There's some difficultly here since Databricks' URLs do not conform to how other databases work.

Sadly, I don't have a Azure Databricks instance that I can test against, so will need your help with this. Thanks.

**Comment by kenshaw** [comment]
@calebeaires I have fixed defining connections in `config.yaml` to properly recognize YAML array syntax. You should be able to define a full connection string now in your `config.yaml`:

```sh
$ cat contrib/config.yaml 
---
# named connections
connections:
  zzz: ["databricks", "token:dapi*****@adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******"]
```

You can then use the named connection `zzz`:

```sh
$ usql
(not connected)=> \c zzz
^C6:00AM ERR error="Post \"https://adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******\": context canceled" connId= corrId= queryId=
error: databricks: request error: error connecting: host=adb-*************.azuredatabricks.net port=443, httpPath=/sql/protocolv1/o/*********/*******: databricks: request error: open session request error: Post "https://adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******": context canceled
```

Note in the above that the URL is now `azuredatabricks.net`.

I've tagged a new release and will publish it as soon as the build has finished.

**Comment by calebeaires** [comment]
@kenshaw 

I use usql into linux ubuntu, and use just the cli with the parameters. Run through a terminal is our primary goal. I can offer you and Azure Databricks connection so you can test. How can I send it to you.

**Comment by kenshaw** [comment]
@calebeaires Sure, I can test it directly. My email is kenshaw <at> gmail. The latest release was published yesterday, it should work just fine though. Please check it out when you can.

**Comment by kenshaw** [comment]
@calebeaires Thank you for sending the credentials. I was able to connect and verify that `usql` will work with Databricks. You need to use this kind of syntax:

```sh
(not connected)=> \c databricks token:****@****.azuredatabricks.net:443/sql/protocolv1/o/****
```

Where the first `****`  is your personal access token, the second is the assigned domain host, and the third is the remote resource/database name.

**Comment by luisvinicius09** [comment]
@kenshaw How can I structure the connection string to be able to use it as shown in the [Using](https://github.com/xo/usql?tab=readme-ov-file#using) and [Database Connection Strings](https://github.com/xo/usql?tab=readme-ov-file#database-connection-strings) sections?

##### Example mentioned [above](https://github.com/xo/usql/issues/466#issuecomment-2155654886) (works fine btw)
> ```shell
> (not connected)=> \c databricks token:****@****.azuredatabricks.net:443/sql/protocolv1/o/****
> ```

#### My goal
> ```shell
> $ usql postgres://booktest@localhost/booktest
> ```

---

I have tried this, but couldn't make it work + I couldn't find any working examples

```shell
usql jdbc+databricks://adb-****.azuredatabricks.net:443/****;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/****;UID=token;PWD=<personal-access-token>;
```

---

I've took some time to look into the [xo/dburl](https://github.com/xo/dburl) repo and [this](https://github.com/xo/dburl/blob/57e186e7b7f9387a60fe2c1b79667cf1d31abde4/dsn.go#L239) raised my attention

```go
func GenDatabricks(u *URL) (string, string, error) {
  { ... }

  s := fmt.Sprintf("token:%s@%s.databricks.com:%s/sql/1.0/endpoints/%s", user, pass, port, host)

  { ... }
}
```

I found it a bit amusing how you're destructuring the URL. If I understand the code correctly and there are no additional procedures, this approach will never work, as you're appending databrick.com to the host. For example, the URL generated by Azure ends with databricks.net.

Could this be why it works in the interactive section but fails when called directly?

**Comment by kenshaw** [comment]
@luisvinicius09 unless the Databricks Go driver changes how this is done, there is no way around this. Each connection has a different URL that's generated by Databricks. If you'd like to rapidly connect to a location, then the best would be to put your configuration in your `$HOME/.config/usql/config.yaml` file:

```yaml
# named connections
connections:
  zzz: ["databricks", "token:dapi*****@adb-*************.azuredatabricks.net:443/sql/protocolv1/o/*********/*******"]
```

You would then be able to use the `zzz` alias to connect either from invoking `usql <CONNECTION NAME>` or with `\c`:

```sh
$ usql zzz
```

(alternately)

```sh
$ usql
Type "help" for help.

(not connected)=>\c zzz
```

This is a limitation of the Databricks driver, and specifically how Databricks requires users to connect to their database.

**Comment by mahiki** [comment]
Just posting here to say that databricks connections dont parse the connection string correctly, in my case in 2025 the token was parsed into the URL part and other malformity. The parsing step swallows the `@` symbol and rearranges the http_path part of the configuration. Completely broken.

This issue did not show up for google searching, so I'll label it here as

>usql databricks connection error 
```
ERR request failed
ERR error="Post \"https://dapi....
request error after 5 attempt(s): Post \"https://dapi...
dial tcp: lookup dapi...no such host
error: databricks: request error: error connecting: host=dapi..
databricks: request error: open session request error: Post "https://dapi...
```

**Comment by kenshaw** [comment]
Because of the way Databricks works, unless the driver is changed, it's not ever going to "cleanly" fit into the URL style. You'll have to always use the full DSN to connect. Please note that you don't have to specifically use the `config.yaml`, you could have done this:

```
(not connected)=> \c databricks token:dapi6XXXXXXXXXXXXX@pp-poo-lab.cloud.databricks.com:443/sql/1.0/warehouses/abc8675309xyz
```
