### ISSUE TITLE
terminal graphics support

### ISSUE THREAD

**Issue by markuman** [xo/usql#474]
Basically graphics supports works for me using kitty.  
But not in usql 0.19.3. Any ideas?

![grafik](https://github.com/user-attachments/assets/5f6b3813-7a07-4af4-8c85-09d14e423eec)

**Comment by dradtke** [comment]
I've bumped into this, too. I can get graphics support to work by starting usql like this:

```sh
$ usql --set TERM_GRAPHICS=kitty
```

But none of these seem to work:

```sh
$ TERM_GRAPHICS=kitty usql
$ USQL_TERM_GRAPHICS=kitty usql
```

I also tried putting this in `~/.config/usql/config.yaml`, but this doesn't work either:

```yaml
init: |
  \set USQL_TERM_GRAPHICS kitty
  \set TERM_GRAPHICS kitty
```

**Comment by kenshaw** [comment]
What version of `usql` are you using?

**Comment by dradtke** [comment]
The latest release, 0.19.3

**Comment by kenshaw** [comment]
I have not tried `usql` with Kitty on Windows (instead, I've tested with WezTerm on Windows). I'll spin up a VM and see what the issue is.

**Comment by dradtke** [comment]
I saw the same issue on Ubuntu, for what it's worth.

**Comment by kenshaw** [comment]
@dradtke @markuman I forgot that I had disabled term graphics for all the tagged releases, as it's still in a "alpha" mode. The `README.md` is a bit ambitious in that sense. The next major release (`v0.20.0`) will have `TERM_GRAPHICS` support enabled by default. Please install via source (`go install github.com/xo/usql@master`) if you'd like to test the mode. I do apologize for the confusion here. 

The next major release is coming extremely soon™️ and will have some really cool terminal graphics based features/functionality.
