### ISSUE TITLE
[feature] Cassandra support

### ISSUE THREAD

**Issue by at15** [xo/usql#48]
Hi, I saw Cassandra in [future plan](https://github.com/xo/usql#future-database-support) and I'd like to give it a shot, I got some questions before start writing the code.

- The cassandra driver [gocql](https://github.com/gocql/gocql) does not implement `database/sql` interface, there is a [thin wrapper](https://github.com/MichaelS11/go-cql-driver). I think it might be better to write the wrapper in usql to reduce dependency
- Cassandra's CQL has some differences with SQL, is there any SQL specific logic I need to be aware of (completion etc.)?
  - Cassandra does not have transaction, it does have batch, which is `BEGIN, APPLY` but no `ROLLBACK`
- testing, it seems test is also in todo list

**Comment by kenshaw** [comment]
Any well written pull request creating a CQL driver would be welcomed. It's not high on my personal list of priorities, but this would be relatively easy to implement, by adding the proper driver entries. A bit of rewriting would be necessary, as the REPL code expects to work with the standard library's database packages/types, and as such could be quite a bit of work. An alternate approach would be to write a package that wraps the CQL driver and registers it as a Go database. Either approach would be roughly the same amount of work.

**Comment by kenshaw** [comment]
@at15 it seems there is a new-ish SQL compatible driver for CQL: https://github.com/MichaelS11/go-cql-driver

I found it only this morning, and finished adding initial Cassandra (well, CQL) support to `usql` just now. 

Please test it out:
```sh
$ go get -u -tags most github.com/xo/usql
$ usql cassandra://cassandra@localhost/
error: cql: invalid username cassandra or password
Enter password: 
Connected with driver cql (Cassandra 3.4.4)
Type "help" for help.

ca:cassandra@localhost=> select * from xxx.y;
                 my_id                 | first_name | last_name  
+--------------------------------------+------------+-----------+
  52e01ecb-4a2f-4274-af46-8464f6032cc8 | aoeu       | test       
(1 rows)

ca:cassandra@localhost=> drop keyspace xxx;
DROP KEYSPACE
ca:cassandra@localhost=>  
```

It was a bit trickier to support this driver, but it's integrated. Let me know how it's working for you.

**Comment by at15** [comment]
@kenshaw I got error from xo/usql/rline when build,  use `vgo build -tags "cassandra"` worked for me

````
# github.com/xo/usql/rline
rline/rline.go:134:15: l.Inst.Config.Output undefined (type *readline.Config has no field or method Output)
rline/rline.go:189:11: undefined: readline.NewCancelableStdin
rline/rline.go:197:20: unknown field 'HistorySearchFold' in struct literal of type readline.Config
rline/rline.go:204:22: unknown field 'FuncFilterInputRune' in struct literal of type readline.Config
````

It is caused by https://github.com/gohxs/readline, btw: the upstream of the fork is active again https://github.com/chzyer/readline/pull/121, maybe switch back to it?

I can connect to cassandra, but when I select something I only get `0 rows` or no response and there is no error when I enter an query with syntax error, it might because I am using Cassandra 2.1, but when using gocql directly, things are working ...

````
cassandra@cqlsh:aaaa> show version
[cqlsh 5.0.1 | Cassandra 2.1.15.1423 | CQL spec 3.2.1 | Native protocol v3
````

**Comment by kenshaw** [comment]
Please note you shouldn't  need to use `dep`. I've switched the project over to using `vgo`. If you did `vgo build` successfully, it would have placed the `usql` binary in the same directory. I'll take a look at the `chzyer/readline` project again, but I'm unlikely to switch it again -- I actually have a non-published, long-running branch of `usql` that has syntax completion that by necessity required me to write my own readline implementation. I'd probably focus on finishing that branch instead of switching back to the `chzyer/readline`.
