### ISSUE TITLE
Comments not respected in usqlrc

### ISSUE THREAD

**Issue by glensc** [xo/usql#493]
In the example, "#" is used for comments:

- https://github.com/xo/usql#runtime-configuration-rc-file

but having "commented out" echo in config, would still execute it:

```
❯ head -n1 ~/.usqlrc
#\echo WELCOME TO THE JUNGLE `date`
```

```
❯ usql
WELCOME TO THE JUNGLE Tue Nov 12 22:19:14 EET 2024





Type "help" for help.

(not connected)=>  
```

**Comment by kenshaw** [comment]
Are you using `master` at the moment? I'm currently reworking command processing.

**Comment by kenshaw** [comment]
Please use `--` in `.usqlrc` if you want to continue using `~/.usqlrc` -- I would suggest switching to the `config.yaml` file, however. The part in the `README.md` is a typo/error on my part, which I'll push a change to shortly.

**Comment by glensc** [comment]
x-ref the commit made:
- https://github.com/xo/usql/commit/4fda83db411369e492fabfe742843a8b0e816fd6

ps: you can refer to tickets if you include their id in commit message: "#493"

**Comment by glensc** [comment]
I installed from brew, version:

```
❯ usql --version
usql 0.19.12
```
