### ISSUE TITLE
How do I turn off the row count output from a select statement

### ISSUE THREAD

**Issue by kishorerathi** [xo/usql#50]
How do I turn off the row count output

```
[Connected with driver mssql (Microsoft SQL Server 11.0.2100.60, RTM, Enterprise Edition: Core-based Licensing (64-bit))
Type "help" for help.

ms:incap@XX.XX.XX.XX:1433/sfstage=> select 'someValue' colName;
   colName   
+-----------+
  someValue  
(1 rows)

```

would like to turn off the "(1 rows)" feedback line.

**Comment by kenshaw** [comment]
There is no way to turn this off yet. While there are plans to fully implement the `\pset` output commands from `psql`, I have no idea on when that might be done -- I do not have a lot of free development time. A pull request implementing it would be most welcome! In the interim, if you are using `usql` for report generation (or some such), I'd suggest passing it through a command line tool (sed, awk, tail, etc.) to strip the line.

**Comment by nineinchnick** [comment]
I gave it a shot in https://github.com/xo/tblfmt/pull/9 - no changes in this repo would be necessary except for bumping the version of tblfmt in go.mod

**Comment by nineinchnick** [comment]
This is now in master and this issue can be closed.

```
sq::memory:=> select 1;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)

sq::memory:=> \pset footer off
Default footer is off.
sq::memory:=> select 1;
+---+
| 1 |
+---+
| 1 |
+---+

sq::memory:=>  
```
