### ISSUE TITLE
[question] Why psql takes so much time

### ISSUE THREAD

**Issue by kaiphat** [xo/usql#500]
I tried to use `usql` and it connects to db instantly(!). The same experience with `dbeaver`. But when i use `psql` or `pgcli` i'm waiting ~1 minute. I suppose it connects with network, but maybe you know strictly why?

**Comment by kaiphat** [comment]
Even to local docker container

**Comment by kenshaw** [comment]
I can't speak for those database utilities, but personally I never have any issues with `psql`. I've played with / used `dbeaver` and `pgcli` in the past, but I don't specifically recall any connection issues. Closing this as this isn't a `usql` issue. Good luck!
