### ISSUE TITLE
Connect to local host with local user by default

### ISSUE THREAD

**Issue by sveniu** [xo/usql#52]
Feature request: Mirror the psql behaviour of [connection defaults](https://www.postgresql.org/docs/10/static/app-psql.html#R2-APP-PSQL-CONNECTING):
- "psql will connect via a Unix-domain socket to a server on the local host"
- "The default user name is your operating-system user name, as is the default database name"

This makes it really easy to fire up psql to do quick testing and prototyping, and I think it would be a useful feature to have in usql.

**Comment by kenshaw** [comment]
Actually, it does this already:

```sh
$ echo $USER
ken
$ usql pg://
error: pq: 28P01: password authentication failed for user "ken"
Enter password:
```

It depends on the database driver, as many databases don't have authentication, and many don't support a "local socket" (ie, a Unix domain socket). Both MySQL and PostgreSQL will work as one would expect, the other databases may or may not.

Additionally, `usql` supports a `.usqlpass` file in your $HOME:
```sh
$ cat $HOME/.usqlpass 
# format is:
# protocol:host:port:dbname:user:pass
postgres:*:*:*:booktest:booktest

mysql:localhost:*:testdb:user:pass
```

Which will automatically set the username and password for a database. This works for all database drivers.
