### ISSUE TITLE
Impala cli support

### ISSUE THREAD

**Issue by rockxsj** [xo/usql#54]
Would you add Impala cli support in future?

**Comment by kenshaw** [comment]
Is there a Go SQL driver for it?

**Comment by rockxsj** [comment]
@kenshaw How about this one:https://github.com/koblas/impalathing

Or may be could use impala ODBC connector?

**Comment by kenshaw** [comment]
That Go package isn't a Go SQL driver. I plan on adding support for databases that don't have a complete Go SQL driver implementation, however that's not likely to happen any time soon.

**Comment by rockxsj** [comment]
@kenshaw It's very nice to hear of this good news!
