### ISSUE TITLE
Oracle: Error output after login

### ISSUE THREAD

**Issue by cloudyster** [xo/usql#63]
Output after starting is 

> Connected with driver ora (<unknown, error: ora: ORA-00942: table or view does not exist>)

caused by `SELECT version FROM v$instance` - the used db-user is not allowed to select `v$instance`

**Comment by kenshaw** [comment]
You can disable this using the `SHOW_HOST_INFORMATION` environment variable. It's documented in `README.md` or on the main page.

#### Host Connection Information

By default, `usql` displays connection information when connecting to a database. This might cause problems with some databases or connections. This can be disabled by setting the system environment variable `USQL_SHOW_HOST_INFORMATION` to `false`:

```sh
$ export USQL_SHOW_HOST_INFORMATION=false
$ usql pg://booktest@localhost
Type "help" for help.

pg:booktest@=>
```

`SHOW_HOST_INFORMATION` is a standard `usql` variable, and can be `\set` or `\unset`. Additionally, it can be passed via the command-line using `-v` or `--set`:

```sh
$ usql --set SHOW_HOST_INFORMATION=false pg://
Type "help" for help.

pg:booktest@=> \set SHOW_HOST_INFORMATION true
pg:booktest@=> \connect pg://
Connected with driver postgres (PostgreSQL 9.6.9)
pg:booktest@=>
```

**Comment by cloudyster** [comment]
Perfect, thanks. Cloudyster

Kenneth Shaw <notifications@github.com> schrieb am So., 24. Juni 2018,
01:35:
