### ISSUE TITLE
[feature] Please add the feature to show the connection list and select from them

### ISSUE THREAD

**Issue by RealDeanZhao** [xo/usql#65]
Hi,
Please add the feature to show the connection list(history or something else) and select from them. This will help when having lots of databases to deal with.

**Comment by nineinchnick** [comment]
This can be implemented by autocompleting the `\c` command with contents of `.usqlpass`. It should be fairly easy to implement now since we have a completer (added in #189)

**Comment by nineinchnick** [comment]
This is done now. You can use:
* history search, by pressing ctrl+r and typing a fragment of the connection string, like the protocol (driver name) or host
* autocomplete, start typing `\c proto...`, press tab and you'll get suggestions

To get better suggestions with autocomplete, add entries to the `.usqlpass` file (see the README for details). Use as few `*` as possible, that is you can have a generic entry with `*` and then more precise entries, for example with hosts that are used often.
