### ISSUE TITLE
error exit code

### ISSUE THREAD

**Issue by elvizlai** [xo/usql#69]
if usql meet error, should return exit -1 or stderr

for example:
x.sql -- wrong sql
```
insert abc; 
123abc
```

`usql mysql://root:pwd@127.0.0.1/test_db -f x.sql`

 only returns

```
Connected with driver mysql (5.7.23)
```

**Comment by super-vip** [comment]
The return code is incorrect. This makes it difficult to capture execution results correctly in scripts or applications.

------- Using usql ----------
[root@dev scripts]# ./bin/usql my://root:110110@192.168.100.100:3306/test -c "insert into apps (id) values ('1')"; echo "return code: $?"
Connected with driver mysql (8.0.13-commercial)
error: mysql: 1062: Duplicate entry '1' for key 'PRIMARY'
return code: 0

[root@dev scripts]# ./bin/usql my://root:110110@192.168.100.100:3306/test -c "insert into apps (iiiiii) values ('2')"; echo "return code: $?"
Connected with driver mysql (8.0.13-commercial)
error: mysql: 1054: Unknown column 'iiiiii' in 'field list'
return code: 0

------- Using MySQL Shell ----------
[root@dev scripts]# ./bin/mysqlsh --sql root:110110@192.168.100.100:3306/test -e "set names 'utf8';insert into apps (iiiiii) values ('2')"; echo "return code: $?"
mysqlx: [Warning] Using a password on the command line interface can be insecure.
ERROR: 1054 (42S22): Unknown column 'iiiiii' in 'field list'
return code: 1

**Comment by sfc-gh-pbennes** [comment]
To the extent usql wants to mimic psql, psql has a variable [ON_ERROR_STOP](https://www.postgresql.org/docs/13/app-psql.html#id-1.9.4.19.7) which can be set which would address this issue. This functionality would be a welcome feature addition to usql for me.

> psql returns 0 to the shell if it finished normally, 1 if a fatal error of its own occurs (e.g., out of memory, file not found), 2 if the connection to the server went bad and the session was not interactive, **and 3 if an error occurred in a script and the variable `ON_ERROR_STOP` was set.**

@kenshaw do you have thoughts one way or the other about this? Is it a feature you'd like to see in usql, is it on the roadmap or would you be open to a PR, and how difficult do you think would it potentially be to implement?
