### ISSUE TITLE
Connection to firebird-database fails

### ISSUE THREAD

**Issue by Rebewslin** [xo/usql#71]
Hi,
connection to my firebird-database fails with:

error: firebirdsql: dial tcp: missing address

Using: usql fb://sysdba:my_password@my_num_ip_address/db_aliasname

(Besides this: Is it possible to access the local fb-sample-database in /Library/Frameworks/Firebird.framework/Versions/A/Resources/examples/empbuild/employee.fdb?)

System is macOS 10.13.6, installed sql successful via homebrew. Thanks in advance for any help!

Nils

**Comment by bkcsfi** [comment]
I have the same problem.

```
usql fb://sysdba:masterkey@my.server.com/opt/database/mydatabase.gdb
error: firebirdsql: dial tcp: missing address
```

I can't post the actual server name, but I can ping the actual server name so its a valid hostname that can be resolved.

**Comment by kenshaw** [comment]
The underlying database driver had changed. I fixed this a while back, but I must have not closed this issue. Please update to the latest code base.

**Comment by bkcsfi** [comment]
thanks, did this get released? I had just downloaded the binary 0.7.0

**Comment by kenshaw** [comment]
No, I have not had time to do a full release.

**Comment by Rebewslin** [comment]
Do you know when the next release is coming? I am not practiced in compiling from sources :-(
