### ISSUE TITLE
Prompt syntax highlighting

### ISSUE THREAD

**Issue by notramo** [xo/usql#73]
The prompt is hard to read.
Example prompt:
`my+unix:user_name@/var/run/mysqld/mysqld.sock=>`
The `user_name` part should be highlighted with one color.
The `/var/run/mysqld/mysqld.sock` part with another color.
Highlighting the `=>` at the end of the prompt with a bright color (in **bold** for multi-line `->`) would help noticing the forgotten `;` at the end of the command.

**Comment by nineinchnick** [comment]
This is now supported since #388 included in [v0.13.5](https://github.com/xo/usql/releases/tag/v0.13.5)
