### ISSUE TITLE
"most" doesn't include apache ignite

### ISSUE THREAD

**Issue by giftig** [xo/usql#75]
I installed via brew, and I see it compiling with drivers = "most". Your readme says most is everything other than oracle and ODBC, and you list an apache ignite driver, but when I chck `\drivers` I see:

```
Available Drivers:
  avatica [av, phoenix]
  clickhouse [ch]
  cockroachdb (postgres) [cr, cdb, crdb, cockroach]
  cql [ca, scy, scylla, datastax, cassandra]
  firebirdsql [fb, firebird]
  hdb [sa, sap, hana, saphana]
  memsql (mysql) [me]
  mssql [ms, sqlserver]
  mymysql [zm, mymy]
  mysql [my, maria, aurora, mariadb, percona]
  n1ql [n1, couchbase]
  pgx [px]
  postgres [pg, pgsql, postgresql]
  presto [pr, prs, prestos, prestodb, prestodbs]
  sqlite3 [sq, file, sqlite]
  tidb (mysql) [ti]
  vitess (mysql) [vt]
  voltdb [vo, vdb, volt]
```

no apache ignite. Not sure if this is an omission from your readme and deliberately excluded from "most" as it's a less common use case, or if it's been accidentally excluded from "most".

**Comment by kenshaw** [comment]
It's definitely part of the `most` tag. Can you give me some more information? Perhaps you need to update the brew tap?

**Comment by giftig** [comment]
@kenshaw I installed the brew tap fresh right before installing, so I assume I'd have the latest version. I don't have my mac at hand right now but if you let me know what other information will help I can provide it when I do.

**Comment by kenshaw** [comment]
@giftig the name of the driver is `avatica`, not `calcite`, as `avatica` is a general purpose protocol, and was the original name. I realize this is 10 months late, but please blame the Apache project. I may add a `calcite` alias at some point to the driver list, but really is not important, as this shouldn't be a barrier to use.

**Comment by giftig** [comment]
No worries, mercifully I didn't have to look at apache ignite for long.
