### ISSUE TITLE
mysql login error

### ISSUE THREAD

**Issue by hellower** [xo/usql#76]
**### mysql id: mig
mysql pwd: Mig#5678**

[good]
[tnt@vpsdime01:/usr/tnt/node_root]
$ usql mysql://mig@localhost:3306/perf
Enter password: 
Connected with driver mysql (5.7.20-19)
Type "help" for help.

my:mig@localhost:3306/perf=>
[tnt@vpsdime01:/usr/tnt/node_root]

[bad]
why this DNS is failed?  (mysql://id:pwd)

[tnt@vpsdime01:/usr/tnt/node_root]
$ usql mysql://mig:'Mig#5678'@localhost:3306/perf
error: mysql: dial tcp: address tcp/Mig: unknown port

[tnt@vpsdime01:/usr/tnt/node_root]
$ usql mysql://mig:Mig#5678@localhost:3306/perf
error: mysql: dial tcp: address tcp/Mig: unknown port

**Comment by kenshaw** [comment]
This is a URL encoding issue. You can use `&#x3A;` for the `:` like the following:

```
usql "mysql://user&#x3a;password@host:9999/dbname"
```

**Comment by kenshaw** [comment]
This is a URL encoding issue. You need to encode special characters in the password. These include things like string quotation marks, etc. The URL simply uses Go's standard `url.Parse` method, and the same encoding rules it accepts, will work for `usql`. The DNS issue is a red herring; the URL parser is confused as to what the actual "port" is, and its interpreting the `Mig` segment as the host name.

For the `#` character, you can use `%23` to URL encode it:
```
usql "mysql://user:my%23pass@host:999/dbname"
```
