### ISSUE TITLE
cross-database list tables query

### ISSUE THREAD

**Issue by eadmaster** [xo/usql#78]
I've found on [Postgres `\dt` is not yet supported](https://github.com/xo/usql/issues/57), and on sqlite `.tables` is not working either.

Btw since [there is no standard way to list all the tables in a dbms ](http://www.sqltutorial.org/sql-list-all-tables/), i'd like to suggest adding a usql-specific query that does just that on every supported db.

**Comment by nineinchnick** [comment]
Is this issue a duplicate of #57?

**Comment by kenshaw** [comment]
Yes.
