### ISSUE TITLE
Use SSL to connect to MySQL

### ISSUE THREAD

**Issue by super-vip** [xo/usql#79]
CMD:
./usql mysql://root:110110@192.168.100.100:3306/op
MSG:
error: mysql: 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.

How to solve it? thanks.

**Comment by kenshaw** [comment]
You need to refer to the underlying [MySQL driver's options](https://github.com/go-sql-driver/mysql#parameters). I would try:

```sh
$ usql 'mysql://root:110100@192.168.100.100/op?tls=true'
```

**Comment by super-vip** [comment]
Using parameters: skip-verify can solve the problem of self-signed certificates.
3Q
./usql mysql://root:110110@192.168.100.100/op?tls=skip-verify
