### ISSUE TITLE
usql 0.71 can not find dependence

### ISSUE THREAD

**Issue by super-vip** [xo/usql#82]
[root@dev scripts]# cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core) 
1 . usql 0.70 can find dependence
[root@dev scripts]# ldd bin/usql; ./bin/usql --version
	not a dynamic executable
usql 0.7.0

2. usql 0.71 can not find dependence
[root@dev scripts]# ldd bin/usql; ./bin/usql --version
	not a dynamic executable
./bin/usql: error while loading shared libraries: libicuuc.so.60: cannot open shared object file: No such file or directory

**Comment by kenshaw** [comment]
Please build from source. Alternately, you can install the `icu` libraries for your system. On CentOS, that would be done with the following:

```
$ yum install -y icu
```

**Comment by ebdavison** [comment]
Installing icu does not fix the binary.  What is provided on Centos 7 with the icu package is: libicuuc.so.50.  The required dependency is libicuuc.so.60.
.
My server does not have a build environment and no go compiler (and installing one is not something I have permissions to do).  Any other suggestions?

**Comment by KaranbirSingh7** [comment]
Incase someone looking to install dependencies for ubuntu:

```bash
sudo apt-get install libicu-dev

```
