### ISSUE TITLE
db2 support

### ISSUE THREAD

**Issue by hhrutter** [xo/usql#85]
Great project!

Any plans to support DB2 in case i missed that?

Thanks
Horst

**Comment by kenshaw** [comment]
You can use the ODBC driver to connect via `usql`. If you follow the instructions for setting up a ODBC connection here: https://medium.com/@zhimin.wen/talking-to-ibm-db2-with-golang-dad8bb6ee4b4 then based on the article you would build `usql` with ODBC support:

```sh
$ go install -tags odbc github.com/xo/usql
```

And connect using the `odbc+<driver>://` schema:

```sh
$ usql odbc+DB2://<hostname>/<database>
```

I have not specifically tried this with DB2 but I've used ODBC with a myriad number of databases without any problems.
