### ISSUE TITLE
Error: undefined: tblfmt.EncodeAll

### ISSUE THREAD

**Issue by yurivict** [xo/usql#86]
rev. 114dc37 fails on FreeBSD:
```
# github.com/xo/usql/handler
handler/handler.go:871:9: undefined: tblfmt.EncodeAll
```

**Comment by kenshaw** [comment]
What version of Go are you using? Please note that we are using Go modules for dependency management. It should build if using the correct module version. The `tblfmt` is currently in massive flux as we finish / better the implementation of that package.

**Comment by yurivict** [comment]
It was a wrong dependency.
Thank you for your help!
