### ISSUE TITLE
odbc database url format

### ISSUE THREAD

**Issue by gregrahn** [xo/usql#87]
I'm able to successfully connect with the ODBC driver using `\c odbc DSN=my-dsn-name` but I'm not able to figure out how to express that using the database url format.  Any suggestions would be appreciated.

**Comment by kenshaw** [comment]
If you have a `odbcinst.ini` configured properly, looking something like the following:
```sh
~/src/go/src/github.com/xo/usql/contrib$ cat db2/odbcinst.ini 
[DB2]
Description=DB2 driver
Driver=/opt/db2/clidriver/lib/libdb2.so
FileUsage = 1
DontDLClose = 1
```
Then the connection string would be `usql odbc+DB2://user:pass@host:port/database`.  The name of the stanza in the `[<NAME>]` is the protocol part.

For example, with PostgreSQL if you have this configuration:
```sh
~/src/go/src/github.com/xo/usql/contrib$ cat postgres/odbcinst.ini 
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=psqlodbca.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1

[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=psqlodbcw.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
```

And you have PostgreSQL running with user `postgres` and password `P4ssw0rd` on the standard 5432 port, the connection string would look like the following:

```sh
$ usql odbc+PostgreSQL+ANSI://postgres:P4ssw0rd@localhost:5432/
```

Alternately could use `odbc+PostgreSQL+Unicode://` as the protocol, which would use the second defined driver.

The `dburl` project is what parses the URLs and translates it into ODBC connection (which, yes I also wrote). It tries to standardize the connection information. If your ODBC definition contains username/password, of course the ODBC driver would be using that instead. If additional parameters are required for ODBC, you may pass them using standard URL `?name=value` style. 

Note that on Windows, we don't use the CGO ODBC driver, but use ADODB's driver, and build a DSN using ADODB as the driver, but telling ADODB to use the ODBC driver.

**Comment by gregrahn** [comment]
Thanks much for the clarification.
