### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by elwarren** [xo/usql#88]
This currently fails to build due to go-ole checksum.  Building with `no_ole` tag still fails because it is in the `go.sum` file.

```
go: verifying github.com/go-ole/go-ole@v1.2.2/go.mod: checksum mismatch
	downloaded: h1:pnvuG7BrDMZ8ifMurTQmxwhQM/odqm9sSqNe5BUI7v4=
	go.sum:     h1:7FAglXiTm7HKlQRDeOQ6ZNUHidzCWXuZWq/1dTyBNF8=
```

**Comment by databigot** [comment]
I got it to work by manually updating the 2 go-ole checksums in the go.sum file, and then building it with go.  but would be nice if this was updated to not need to.
