### ISSUE TITLE
Migrate to goracle.v2

### ISSUE THREAD

**Issue by lbarcaroli** [xo/usql#91]
Hi! Thanks for this great piece of software :)

I would just like to point you to [this issue](https://github.com/rana/ora/issues/264) I opened to `rana/ora.v4`. They said (someone who seems quite active on the bug tracker and apparently knows what he is talking about) that the project is unmaintained and suggest switching to [`gopkg.in/goracle.v2`](https://gopkg.in/goracle.v2).

Do you have any plans regarding this?

Thanks again

**Comment by kenshaw** [comment]
I'm open for a well written PR for this, but I've looked into doing this, and it would be a significant effort to change to the `goracle` implementation with very minimal (if any) benefits.

**Comment by gedw99** [comment]
In the Related Issue the maintainer says that github.com/rana/ora is unmaintained .

Sounds like a move to the Oracle driver is the only future proofed way to move forward IMHO.

**Comment by gedw99** [comment]
What about https://github.com/mattn/go-oci8 ?
Looks well maintained !

**Comment by kenshaw** [comment]
I've already changed the code over to `goracle`. However, because Oracle intends to make it impossible for developers to use their software, I haven't been able to test/debug the `goracle` driver in conjunction with `usql`. Hypothetically it works.
