### ISSUE TITLE
DB2-Odbc driver issue libd2.so

### ISSUE THREAD

**Issue by DavidPf94** [xo/usql#95]
Hey guys,

i try to run a docker container which includes your usql-client to connect to db2-databases
I used : 
`go get -u -tags odbc github.com/xo/usql`

And added following to /etc/odbcinst.ini:

> [DB2]
Description=DB2 driver
Driver=/opt/db2/clidriver/lib/libdb2.so
FileUsage = 1
DontDLClose = 1

But receiving following error when try to connect to my db2 instance: `Can't open lib '/opt/db2/clidriver/lib/libdb2.so' : file not found`

Where can I get that libdb2.so file?

**Comment by kenshaw** [comment]
You need to have that path in your `ld` config. Try something like:

```sh
$ export LD_LIBRARY_PATH=/opt/db2/clidriver/lib:$LD_LIBRARY_PATH
$ usql
```

If that works, you need to make that change persistent by modifying your system's `ld` config. That can usually be done by something like the following:

```sh
$ echo '/opt/db2/clidriver/lib' | sudo tee -a /etc/ld.so.conf.d/99-db2.conf
$ sudo ldconfig
```
