### ISSUE TITLE
[Feature Request] Inclusion of Vertica Support

### ISSUE THREAD

**Issue by huebnerr** [xo/usql#98]
Requesting addition of Vertica support based on:

https://github.com/vertica/vertica-sql-go

driver.

**Comment by kenshaw** [comment]
I've added initial Vertica support. I'll do some more testing, before I tag a release and build release binaries.

**Comment by huebnerr** [comment]
Thank you very much. Our customers and internal teams will certainly be happy to learn about this.

**Comment by kenshaw** [comment]
@huebnerr point of reference, in the future, if you're asking for a specific feature support in an open source project for your company, it's best to, eg, write it and submit it yourself. Part of `usql`'s mission is to cover every SQL database (which is why I quickly added the support for Vertica), but I would have much rather preferred if you / Vertica submitted a PR.

**Comment by huebnerr** [comment]
Absolutely would've been happy to do so. On the other hand, it's great having your implementation there. :) We'll be watching and responding to bug fixes as needed.

Roger

On Nov 14, 2019 4:23 PM, Kenneth Shaw <notifications@github.com> wrote:

@huebnerr<https://github.com/huebnerr> point of reference, in the future, if you're asking for a specific feature support in an open source project for your company, it's best to, eg, write it and submit it yourself. Part of usql's mission is to cover every SQL database (which is why I quickly added the support for Vertica), but I would have much rather preferred if you / Vertica submitted a PR.

**Comment by kenshaw** [comment]
@huebnerr -- please note that I don't know if the Vertica SQL driver for Go works the way it's supposed to, as it doesn't recover from errors. That is, with `usql`, you can't issue queries to Vertica after you've encountered an error. For example, if you type in a bad SQL query:

```sh
ken@ken-desktop:~/src/go/src/github.com/xo/usql$ ./usql ve://dbadmin@localhost/dbadmin
error: vertica: 28000: Invalid username or password
Enter password: 
Connected with driver vertica (Vertica Analytic Database v9.2.0-7)
WELCOME TO THE JUNGLE Fri 15 Nov 2019 07:46:24 AM WIB
Type "help" for help.

ve:dbadmin@localhost/dbadmin=> select 1+2;
 ?column? 
----------
        3 
(1 row)

ve:dbadmin@localhost/dbadmin=> select 1+'aoeu';
error: vertica: 22V02: Invalid input syntax for integer: "aoeu"
ve:dbadmin@localhost/dbadmin=> select 'aoeu';
^C
ken@ken-desktop:~/src/go/src/github.com/xo/usql$
``` 
Please note that the third query never completes. One needs to reconnect / create a new database connection in order to complete queries. This is not how the other SQL drivers work. I'd appreciate feedback on whether or not that's a function/limitation of Vertica, or of the underlying Go driver.

**Comment by huebnerr** [comment]
Strange. Let me have a look!

On Nov 14, 2019 6:49 PM, Kenneth Shaw <notifications@github.com> wrote:

@huebnerr<https://github.com/huebnerr> -- please note that I don't know if the Vertica SQL driver for Go works the way it's supposed to, as it doesn't recover from errors. That is, with usql, you can't issue queries to Vertica after you've encountered an error. For example, if you type in a bad SQL query:

ken@ken-desktop:~/src/go/src/github.com/xo/usql$ ./usql ve://dbadmin@localhost/dbadmin
error: vertica: 28000: Invalid username or password
Enter password:
Connected with driver vertica (Vertica Analytic Database v9.2.0-7)
WELCOME TO THE JUNGLE Fri 15 Nov 2019 07:46:24 AM WIB
Type "help" for help.

ve:dbadmin@localhost/dbadmin=> select 1+2;
 ?column?
----------
        3
(1 row)

ve:dbadmin@localhost/dbadmin=> select 1+'aoeu';
error: vertica: 22V02: Invalid input syntax for integer: "aoeu"
ve:dbadmin@localhost/dbadmin=> select 'aoeu';
^C
ken@ken-desktop:~/src/go/src/github.com/xo/usql$

Please note that the third query never completes. One needs to reconnect / create a new database connection in order to complete queries. This is not how the other SQL drivers work. I'd appreciate feedback on whether or not that's a function/limitation of Vertica, or of the underlying Go driver.

**Comment by kenshaw** [comment]
I've just tagged a new release, and will be pushing out builds later today.

**Comment by huebnerr** [comment]
I'll dig into the issue today. It's not something I'm aware of happening before although some bug might have been introduced. Thanks for the heads up. Will let you know shortly.

**Comment by huebnerr** [comment]
Able to replicate without usql. It seems to only happen during parse errors (all other kinds of errors recover correctly).

**Comment by huebnerr** [comment]
@kenshaw, please check https://github.com/xo/usql/pull/101

This should fix the observed problem. Please let me know of any other issues you might find.
