### ISSUE TITLE
[Question] Does the database connected with ODBC only support DB2 and PostgreSQL?

### ISSUE THREAD

**Issue by francis-du** [xo/usql#99]
Does the database connected with ODBC only support DB2 and PostgreSQL?An exception occurs when I connect to SpliceMachine Database:
![image](https://user-images.githubusercontent.com/25944814/68760600-320a3680-064d-11ea-8908-e4aeab5ddfad.png)

**Comment by kenshaw** [comment]
It supports any ODBC database. Please check with the `isql` command line tool, and see if you're able to connect through that. my guess here is that you're simply missing the `[URL]` configuration in your `odbcinst.ini` file. 

For the record, I've tested ODBC connections for MySQL, PostgreSQL, and Microsoft SQL Server previously. I'm closing this issue out, but please feel free to reopen it if you find that it is anything other than a missing `[URL]` stanza in your `odbcinst.ini` configuration.
